"use client";
import { useEffect, useRef, useState } from "react";
import { apiRequest, AuthError, getToken, subscribeSession } from "../auth/api";
import { useClinicRequest, type Page } from "../clinics/api";
import { DirectoryTable } from "../directory/DirectoryPrimitives";
import { Pagination } from "../directory/Controls";
import type { Snapshot } from "./wizard";
import Modal from "../clinics/Modal";
import styles from "../clinics/clinics.module.css";
import layout from "./wizard.module.css";

type Attachment={id:number;visit_id:number;visit_no:string;visit_date:string;title:string;original_filename:string;extension:string;size:number;uploaded_at:string;lock_version:number};
type Upload={key:string;file:File;title:string;request:string;ticket?:number;progress:number;state:"ready"|"uploading"|"failed"|"saved";error?:string};
export function AttachmentHistory({facility,dossier,visit,caps,revision=0,onVoid}:{facility:number;dossier:number;visit?:number;caps:Record<string,boolean>;revision?:number;onVoid?:(a:Attachment)=>void}){
  const [all,setAll]=useState(false),[page,setPage]=useState(1),[from,setFrom]=useState(""),[to,setTo]=useState(""),[type,setType]=useState(""),[direction,setDirection]=useState("desc");
  const [error,setError]=useState(""),[busy,setBusy]=useState(false);const pending=useRef<AbortController|null>(null);
  useEffect(()=>()=>pending.current?.abort(),[]);
  const q=new URLSearchParams({facility_id:String(facility),page:String(page),per_page:"10",direction});if(visit&&!all)q.set("visit_id",String(visit));if(from)q.set("from",from);if(to)q.set("to",to);if(type)q.set("extension",type);
  const list=useClinicRequest<Page<Attachment>>(caps.attachments_view?`dossiers/${dossier}/attachments?${q}`:null,true,false,revision);
  async function download(a:Attachment){if(pending.current||!caps.attachments_download)return;const c=new AbortController();pending.current=c;setBusy(true);setError("");try{const {blob}=await apiRequest<{blob:Blob}>(`dossiers/${dossier}/visits/${a.visit_id}/attachments/${a.id}/download?facility_id=${facility}`,{signal:c.signal},"blob");if(c.signal.aborted)return;const url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=a.original_filename;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:"تعذر التنزيل");}finally{pending.current=null;if(!c.signal.aborted)setBusy(false);}}
  if(!caps.attachments_view)return <p className={styles.hint}>عرض بيانات المرفقات يحتاج صلاحية مستقلة.</p>;
  return <section className={layout.diagnosis}><div className={layout.diagnosisHeader}><h4>{all||!visit?"مرفقات جميع الزيارات":"مرفقات الزيارة المختارة"}</h4>{visit&&<button type="button" className={styles.secondary} onClick={()=>{setAll(!all);setPage(1);}}>{all?"مرفقات هذه الزيارة فقط":"استعراض مرفقات جميع الزيارات"}</button>}</div><div className={styles.filters}><label>تاريخ الزيارة من<input type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1);}}/></label><label>تاريخ الزيارة إلى<input type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(1);}}/></label><label>نوع الملف<select value={type} onChange={e=>{setType(e.target.value);setPage(1);}}><option value="">الكل</option>{["pdf","xls","xlsx","jpg","jpeg","png","webp"].map(t=><option key={t}>{t}</option>)}</select></label><label>ترتيب تاريخ الزيارة<select value={direction} onChange={e=>{setDirection(e.target.value);setPage(1);}}><option value="desc">الأحدث</option><option value="asc">الأقدم</option></select></label></div>{list.loading&&<p role="status">جارٍ تحميل المرفقات…</p>}{(list.error||error)&&<p role="alert">{list.error||error}<button type="button" className={styles.secondary} onClick={list.retry}>إعادة المحاولة</button></p>}{list.data&&<><DirectoryTable label="مرفقات بطاقة المريض" headers={["الملف","الزيارة","النوع والحجم","الإجراء"]}>{list.data.data.map(a=><tr key={a.id}><td>{a.title}<p className={styles.hint}>{a.original_filename}</p></td><td><bdi>{a.visit_no}</bdi><p>{a.visit_date}</p></td><td>{a.extension.toUpperCase()} · {Math.ceil(a.size/1024)} KB</td><td>{caps.attachments_download?<button type="button" disabled={busy} className={styles.secondary} onClick={()=>void download(a)}>تنزيل</button>:"عرض بيانات فقط"}{onVoid&&caps.attachments_void&&a.visit_id===visit&&<button type="button" className={styles.danger} disabled={busy} onClick={()=>onVoid(a)}>إبطال المرفق</button>}</td></tr>)}{!list.data.data.length&&<tr><td colSpan={4}>لا توجد مرفقات محفوظة مطابقة.</td></tr>}</DirectoryTable><Pagination meta={list.data.meta} onPage={setPage}/></>}</section>;
}
export default function Attachments({facility,snapshot,caps,onSaved,onPending,blocked}:{facility:number;snapshot:Snapshot;caps:Record<string,boolean>;onSaved:(s:Snapshot)=>void;onPending:(v:boolean)=>void;blocked:boolean}){
  const [files,setFiles]=useState<Upload[]>([]);const current=useRef<XMLHttpRequest|null>(null),pending=useRef<AbortController|null>(null),mounted=useRef(true),token=useRef(getToken());
  const [busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const [voidRow,setVoidRow]=useState<Attachment|null>(null),[voidReason,setVoidReason]=useState("");
  const voidRequest=useRef<{body:string;id:string}|null>(null);
  const visit=snapshot.visit!;const path=`dossiers/${snapshot.id}/visits/${visit.id}`;
  useEffect(()=>{mounted.current=true;const stop=subscribeSession(()=>{if(getToken()!==token.current){current.current?.abort();pending.current?.abort();}});return()=>{mounted.current=false;current.current?.abort();pending.current?.abort();stop();};},[]);
  useEffect(()=>{onPending(files.some(f=>f.state!=="saved"));},[files,onPending]);
  const update=(key:string,fields:Partial<Upload>)=>{if(mounted.current)setFiles(rows=>rows.map(r=>r.key===key?{...r,...fields}:r));};
  async function refresh(signal:AbortSignal){const s=await apiRequest<Snapshot>(`${path}/progress?facility_id=${facility}`,{signal});if(mounted.current&&!signal.aborted)onSaved(s);}
  async function upload(row:Upload){
    if(current.current||pending.current||blocked||!caps.attachments_upload)return;
    const c=new AbortController();pending.current=c;setBusy(true);setMessage("");update(row.key,{state:"uploading",error:undefined});
    try{
      let ticket=row.ticket;
      if(!ticket){const r=await apiRequest<{upload_id:number}>(`${path}/uploads`,{method:"POST",signal:c.signal,body:JSON.stringify({facility_id:facility,lock_version:visit.lock_version,request_id:row.request,title:row.title,original_filename:row.file.name})});ticket=r.upload_id;update(row.key,{ticket});}
      if(c.signal.aborted)return;
      await new Promise<void>((resolve,reject)=>{const xhr=new XMLHttpRequest();current.current=xhr;xhr.open("POST",`/hospital-api/${path}/uploads/${ticket}?facility_id=${facility}`);xhr.setRequestHeader("Accept","application/json");const bearer=getToken();if(bearer)xhr.setRequestHeader("Authorization",`Bearer ${bearer}`);xhr.timeout=120000;xhr.upload.onprogress=e=>{if(e.lengthComputable)update(row.key,{progress:Math.round(e.loaded/e.total*100)});};xhr.onload=()=>{if(getToken()!==token.current||c.signal.aborted)return reject(new Error("تغيرت الجلسة؛ أعد فتح الصفحة."));const body=(()=>{try{return JSON.parse(xhr.responseText);}catch{return null;}})();if(xhr.status>=200&&xhr.status<300)resolve();else reject(new Error(body?.errors?.file?.[0]??"تعذر حفظ الملف؛ المسودة باقية. أعد المحاولة أو ألغِ محاولة الرفع."));};xhr.onerror=xhr.ontimeout=()=>reject(new Error("تعذر رفع الملف؛ أعد المحاولة لهذا الملف فقط."));xhr.onabort=()=>reject(new Error("أُلغي الرفع."));c.signal.addEventListener("abort",()=>xhr.abort(),{once:true});const form=new FormData();form.append("file",row.file);xhr.send(form);});
      update(row.key,{state:"saved",progress:100});await refresh(c.signal);
    }catch(e){if(!c.signal.aborted)update(row.key,{state:"failed",error:e instanceof Error?e.message:"تعذر الرفع"});}
    finally{current.current=null;pending.current=null;if(mounted.current)setBusy(false);}
  }
  async function voidAttachment(){
    if(!voidRow||pending.current||current.current||blocked||!caps.attachments_void||!voidReason.trim())return;
    const c=new AbortController();pending.current=c;setBusy(true);setMessage("");
    const body={facility_id:facility,lock_version:visit.lock_version,attachment_lock_version:voidRow.lock_version,void_reason:voidReason};
    const signature=JSON.stringify(body);if(voidRequest.current?.body!==signature)voidRequest.current={body:signature,id:crypto.randomUUID()};
    try{const saved=await apiRequest<Snapshot>(`${path}/attachments/${voidRow.id}/void`,{method:"POST",signal:c.signal,body:JSON.stringify({...body,request_id:voidRequest.current.id})});if(!c.signal.aborted){onSaved(saved);setVoidRow(null);setVoidReason("");voidRequest.current=null;}}
    catch(e){if(!c.signal.aborted)setMessage(e instanceof Error?e.message:"تعذر إبطال المرفق؛ السبب محفوظ للمحاولة مجددًا.");}
    finally{pending.current=null;if(mounted.current)setBusy(false);}
  }
  async function cancel(row:Upload){if(busy)return;setMessage("");if(row.ticket){const c=new AbortController();pending.current=c;setBusy(true);try{await apiRequest(`${path}/uploads/${row.ticket}/cancel`,{method:"POST",signal:c.signal,body:JSON.stringify({facility_id:facility})});}catch(e){if(!c.signal.aborted)setMessage(e instanceof AuthError?e.message:"تعذر إلغاء المحاولة؛ حاول مجددًا.");return;}finally{pending.current=null;if(mounted.current)setBusy(false);}}if(mounted.current)setFiles(rows=>rows.filter(r=>r.key!==row.key));}
  return <><section className={layout.diagnosis}><h4>رفع مرفقات الزيارة</h4><p className={styles.hint}>PDF وExcel وصور JPEG وPNG وWebP. تُحفظ الملفات بصورة خاصة؛ المرفقات اختيارية. إنهاء كل محاولة أو إلغاؤها مطلوب قبل الإكمال.</p>{caps.attachments_upload&&<label>اختيار ملفات<input type="file" multiple accept=".pdf,.xls,.xlsx,.jpg,.jpeg,.png,.webp" disabled={busy||blocked} onChange={e=>{const chosen=Array.from(e.target.files??[]);setFiles(rows=>[...rows,...chosen.map(file=>({key:crypto.randomUUID(),request:crypto.randomUUID(),file,title:file.name.replace(/\.[^.]+$/,""),progress:0,state:"ready" as const}))]);e.target.value="";}}/></label>}{files.map(row=><div key={row.key} className={layout.diagnosis}><strong>{row.file.name}</strong><label>عنوان الملف *<input value={row.title} maxLength={200} disabled={busy||!!row.ticket||row.state==="saved"} onChange={e=>update(row.key,{title:e.target.value})}/></label>{row.state==="uploading"&&<progress max={100} value={row.progress} aria-label={`تقدم رفع ${row.file.name}`}/>}<p role={row.error?"alert":"status"}>{row.error??(row.state==="saved"?"تم حفظ الملف":row.state==="uploading"?`${row.progress}% · جارٍ رفع الملف وحفظه`:"لم يُرفع بعد")}</p>{row.state!=="saved"&&<div className={styles.actions}><button type="button" className={styles.secondary} disabled={busy||blocked||!row.title.trim()} onClick={()=>void upload(row)}>{row.state==="failed"?"إعادة رفع هذا الملف":"رفع الملف"}</button><button type="button" className={styles.secondary} disabled={busy} onClick={()=>void cancel(row)}>إلغاء هذا الملف</button></div>}</div>)}{message&&<p role="alert">{message}</p>}<button type="button" className={styles.secondary} disabled={busy} onClick={()=>{const c=new AbortController();pending.current=c;setBusy(true);void refresh(c.signal).catch(()=>setMessage("تعذر تحديث بيانات المرفقات؛ حاول مجددًا.")).finally(()=>{pending.current=null;if(mounted.current)setBusy(false);});}}>تحديث الملفات المحفوظة</button></section><AttachmentHistory facility={facility} dossier={snapshot.id} visit={visit.id} caps={caps} revision={visit.lock_version} onVoid={!blocked&&visit.status==="draft"?a=>{setVoidRow(a);setVoidReason("");setMessage("");}:undefined}/>{voidRow&&<Modal title="إبطال المرفق" busy={busy} onClose={()=>setVoidRow(null)}><p>سيُستبعد المرفق من العرض الحالي مع الاحتفاظ بالملف وتاريخ التدقيق.</p><label>سبب الإبطال *<textarea value={voidReason} maxLength={255} onChange={e=>setVoidReason(e.target.value)}/></label>{message&&<p role="alert">{message}</p>}<div className={styles.actions}><button type="button" className={styles.danger} disabled={busy||!voidReason.trim()} onClick={()=>void voidAttachment()}>تأكيد الإبطال</button><button type="button" className={styles.secondary} disabled={busy} onClick={()=>setVoidRow(null)}>إلغاء</button></div></Modal>}</>;
}
