"use client";
import { useState } from "react";
import ClinicDoctorPicker from "./ClinicDoctorPicker";
import Picker from "./DossierPicker";
import { NewDirectoryEntry } from "./DiagnosisEditor";
import { type ClinicalDraft, type Context, type Occurrence, type SavedRow, outcomeLabels } from "./clinical";
import styles from "../clinics/clinics.module.css";
import layout from "./wizard.module.css";

type ErrorDisplay=(key:string)=>React.ReactNode;
export function ClinicalContext({value,change,facility,date,prefix,doctorKey="doctor_id",clinicKey="clinic_id",label,error}: {value:Context;change:(v:Context)=>void;facility:number;date:string;prefix:string;doctorKey?:string;clinicKey?:string;label:string;error:ErrorDisplay}) {
  return <><div><Picker name={`${prefix}${clinicKey}`} label={`العيادة · ${label}`} path={`dossiers/options/clinics?facility_id=${facility}`} selected={value.clinic} onSelect={clinic=>change({clinic,doctor:clinic.id===value.clinic?.id?value.doctor:null})}/>{error(`${prefix}${clinicKey}`)}</div><div><ClinicDoctorPicker facility={facility} clinic={value.clinic} date={date} name={`${prefix}${doctorKey}`} label={`الطبيب المسؤول · ${label}`} selected={value.doctor} onSelect={doctor=>change({...value,doctor})}/>{error(`${prefix}${doctorKey}`)}</div></>;
}
function Removal({row,change,remove,label,prefix,error}:{row:SavedRow;change:(v:SavedRow)=>void;remove:()=>void;label:string;prefix:string;error:ErrorDisplay}) {
  return <><button type="button" className={`${styles.secondary} ${row.remove?"":styles.dangerText}`} onClick={()=>row.id?change({...row,remove:!row.remove}):remove()}>{row.remove?"التراجع عن الإزالة":`إزالة ${label}`}</button>{row.remove&&<label>سبب التصحيح والإزالة *<input name={`${prefix}.void_reason`} value={row.void_reason??""} onChange={e=>change({...row,void_reason:e.target.value})}/>{error(`${prefix}.void_reason`)}</label>}</>;
}
export default function ClinicalEditor({section,value,change,facility,date,canCreateMedication,error}:{section:number;value:ClinicalDraft;change:(d:ClinicalDraft)=>void;facility:number;date:string;canCreateMedication:boolean;error:ErrorDisplay}) {
  const [adding,setAdding]=useState<string|null>(null);
  const p=value.prescription,o=value.outcome;
  if(section===3) return <>{(["procedures","services"] as const).map(kind=>{const title=kind==="services"?"الخدمات":"الإجراءات";const singular=kind==="services"?"الخدمة":"الإجراء";return <section key={kind} className={layout.diagnosis}><h4>{title}</h4><p className={styles.hint}>التاريخ هو تاريخ الزيارة الفعلي. يمكن مراجعة هذا القسم وحفظه دون بنود.</p>{value[kind].map((row,i)=>{const prefix=`${kind}.${i}`;const update=(r:Occurrence)=>change({...value,[kind]:value[kind].map(x=>x.key===row.key?r:x)});return <section key={row.key} className={layout.diagnosis} aria-label={`${singular} ${i+1}`}><div className={layout.diagnosisHeader}><h4>{singular} {i+1}{row.id?" · محفوظ":""}</h4><Removal row={row} change={r=>update({...row,...r})} remove={()=>change({...value,[kind]:value[kind].filter(x=>x.key!==row.key)})} label={singular} prefix={prefix} error={error}/></div>{!row.remove&&<div className={styles.fields}><div className={styles.full}><Picker name={`${prefix}.catalog_id`} label={`${singular} من الدليل ${i+1}`} path={`dossiers/options/${kind}?facility_id=${facility}`} selected={row.catalog} onSelect={catalog=>update({...row,catalog})}/>{error(`${prefix}.catalog_id`)}</div><ClinicalContext value={row} change={ctx=>update({...row,...ctx})} facility={facility} date={date} prefix={`${prefix}.`} label={`${singular} ${i+1}`} error={error}/><label className={styles.full}>ملاحظة {singular}<textarea name={`${prefix}.note`} value={row.note} rows={3} maxLength={10000} onChange={e=>update({...row,note:e.target.value})}/>{error(`${prefix}.note`)}</label></div>}</section>})}{!value[kind].length&&<p>لا توجد بنود في المسودة.</p>}<div><button type="button" className={styles.secondary} onClick={()=>change({...value,[kind]:[...value[kind],{key:crypto.randomUUID(),catalog:null,clinic:null,doctor:null,note:""}]})}>إضافة {singular} للزيارة</button></div></section>})}</>;
  return <><section className={layout.diagnosis}><h4>الوصفة الطبية</h4><p className={styles.hint}>وصفة واحدة تضم عدة أدوية وطبيبًا مسؤولًا عنها. الوصفة لا تسجل صرف الدواء أو إعطاءه.</p>{!p?<button type="button" className={styles.secondary} onClick={()=>change({...value,prescription:{clinic:null,doctor:null,prescribed_on:date,note:"",items:[]}})}>إضافة وصفة للزيارة</button>:<><Removal row={p} change={r=>change({...value,prescription:{...p,...r}})} remove={()=>change({...value,prescription:null})} label="الوصفة" prefix="prescription" error={error}/>{!p.remove&&<><div className={styles.fields}><ClinicalContext value={p} change={ctx=>change({...value,prescription:{...p,...ctx}})} facility={facility} date={date} prefix="prescription." doctorKey="prescribing_staff_id" clinicKey="prescribing_clinic_id" label="الوصفة" error={error}/><label>تاريخ الوصفة *<input name="prescription.prescribed_on" type="date" value={p.prescribed_on} onChange={e=>change({...value,prescription:{...p,prescribed_on:e.target.value}})}/>{error("prescription.prescribed_on")}</label><label>ملاحظة عامة للوصفة<textarea name="prescription.note" rows={3} value={p.note} onChange={e=>change({...value,prescription:{...p,note:e.target.value}})}/>{error("prescription.note")}</label></div>{p.items.map((item,i)=>{const update=(v:typeof item)=>change({...value,prescription:{...p,items:p.items.map(x=>x.key===item.key?v:x)}});return <section key={item.key} className={layout.diagnosis} aria-label={`دواء الوصفة ${i+1}`}><div className={layout.diagnosisHeader}><h4>الدواء {i+1}</h4><Removal row={item} change={r=>update({...item,...r})} remove={()=>change({...value,prescription:{...p,items:p.items.filter(x=>x.key!==item.key)}})} label="الدواء" prefix={`prescription.items.${i}`} error={error}/></div>{!item.remove&&<div className={styles.fields}><div><Picker name={`prescription.items.${i}.medication_id`} label={`الدواء من الدليل ${i+1}`} path={`dossiers/options/medications?facility_id=${facility}`} selected={item.medication} onSelect={medication=>update({...item,medication})}/>{error(`prescription.items.${i}.medication_id`)}{canCreateMedication&&<button type="button" className={styles.secondary} onClick={()=>setAdding(item.key)}>إضافة دواء إلى الدليل</button>}</div><label>ملاحظة خاصة بالدواء<textarea name={`prescription.items.${i}.note`} rows={3} value={item.note} onChange={e=>update({...item,note:e.target.value})}/>{error(`prescription.items.${i}.note`)}</label></div>}</section>})}{error("prescription.items")}<button type="button" className={styles.secondary} onClick={()=>change({...value,prescription:{...p,items:[...p.items,{key:crypto.randomUUID(),medication:null,note:"",display_order:p.items.length}]}})}>إضافة دواء للوصفة</button></>}</>}</section>
    <section className={layout.diagnosis}><h4>نتيجة الزيارة</h4><p className={styles.hint}>يمكن حفظ المسودة دون نتيجة، لكن إكمال الزيارة يحتاج نتيجة واحدة صريحة.</p>{!o?<button type="button" className={styles.secondary} onClick={()=>change({...value,outcome:{clinic:null,doctor:null,code:"",outcome_on:date,note:"",referral_target:"",outgoing_referral_date:"",outgoing_referral_reason:""}})}>تسجيل نتيجة الزيارة</button>:<><Removal row={o} change={r=>change({...value,outcome:{...o,...r}})} remove={()=>change({...value,outcome:null})} label="النتيجة" prefix="outcome" error={error}/>{!o.remove&&<div className={styles.fields}><label>نتيجة الزيارة *<select name="outcome.code" value={o.code} onChange={e=>change({...value,outcome:{...o,code:e.target.value,...e.target.value!=="DOS-REFER"?{referral_target:"",outgoing_referral_date:"",outgoing_referral_reason:""}:{}}})}><option value="">اختر النتيجة</option>{Object.entries(outcomeLabels).map(([code,label])=><option key={code} value={code}>{label}</option>)}</select>{error("outcome.code")}</label><label>تاريخ النتيجة *<input name="outcome.outcome_on" type="date" value={o.outcome_on} onChange={e=>change({...value,outcome:{...o,outcome_on:e.target.value}})}/>{error("outcome.outcome_on")}</label><ClinicalContext value={o} change={ctx=>change({...value,outcome:{...o,...ctx}})} facility={facility} date={date} prefix="outcome." label="نتيجة الزيارة" error={error}/>{o.code==="DOS-REFER"&&<><h4 className={layout.subheading}>الإحالة الصادرة إلى مشفى آخر</h4>{([["referral_target","مشفى الوجهة","text"],["outgoing_referral_date","تاريخ الإحالة الصادرة","date"],["outgoing_referral_reason","سبب الإحالة الصادرة","text"]] as const).map(([key,label,type])=><label key={key}>{label} *<input name={`outcome.${key}`} type={type} value={o[key]} onChange={e=>change({...value,outcome:{...o,[key]:e.target.value}})}/>{error(`outcome.${key}`)}</label>)}</>}<label className={styles.full}>ملاحظة النتيجة<textarea name="outcome.note" rows={3} value={o.note} onChange={e=>change({...value,outcome:{...o,note:e.target.value}})}/>{error("outcome.note")}</label></div>}</>}</section>
    {adding&&<NewDirectoryEntry kind="medication" facility={facility} onClose={()=>setAdding(null)} onSaved={medication=>{if(p)change({...value,prescription:{...p,items:p.items.map(x=>x.key===adding?{...x,medication}:x)}});setAdding(null);}}/>}
  </>;
}
