"use client";

import { usePathname, useRouter, useSearchParams } from "next/navigation";
import Link from "next/link";
import { useState } from "react";
import {modalities,treatmentColumns} from "./oncology";
import { dispositionLabels } from "./pathology";
import PathologyPanel from "./PathologyPanel";
import OncologyPanel from "./OncologyPanel";
import DossierAuditHistory from "./DossierAuditHistory";
import DossierHistoryReport from "./DossierHistoryReport";
import DossierReports, { reportColumns, defaultColumns } from "./DossierReports";
import { AttachmentHistory } from "./Attachments";
import { LuHospital, LuPlus, LuSearch } from "react-icons/lu";
import { useIdentity } from "../auth/AuthenticatedLayout";
import { directoryFacility } from "../directory/facilityContext";
import { DirectoryBack, DirectoryRowActions, DirectoryTable } from "../directory/DirectoryPrimitives";
import { Pagination, LongText, ColumnMenu } from "../directory/Controls";
import { useClinicRequest, type Page } from "../clinics/api";
import useClinicSearch from "../clinics/useClinicSearch";
import { type Dossier, type DossierRow, type Visit, type ClinicalItem, historyLabels, treatmentLabels, sourceLabels, patientBirthDate } from "./api";
import styles from "../clinics/clinics.module.css";
import cardStyles from "./patient-cards.module.css";
import type { WizardOptions } from "./wizard";

export default function DossierScreen({ id }: { id?: string }) {
  const { access, user } = useIdentity(); const params = useSearchParams();
  const { entry } = directoryFacility(access, "dossiers.view", params.get("facility_id"));
  if (!entry || (id && !/^[1-9]\d*$/.test(id))) return <section className={styles.status}><h2>بطاقات المرضى غير متاحة</h2><p role="alert">تعذّر تحديد مشفى مصرح لك بالوصول إلى بطاقات مرضاه. راجع مسؤول الصلاحيات.</p></section>;
  return <div className={styles.screen}><div className={styles.context}><LuHospital aria-hidden="true" /><span>المشفى</span><strong>{entry.facility.name_ar}</strong></div>{id ? <Detail key={`${user.id}:${entry.facility.id}:${id}`} id={id} facility={entry.facility.id} /> : <Listing key={`${user.id}:${entry.facility.id}`} facility={entry.facility.id} />}</div>;
}
function Failure({ error, retry }: { error: string; retry: () => void }) { return <div className={styles.status}><p role="alert">{error}</p><button className={styles.secondary} onClick={retry}>إعادة المحاولة</button></div>; }
function StatusBadge({ status, visit = false }: { status: "draft" | "active" | "complete"; visit?: boolean }) {
  const text = status === "draft" ? "مسودة" : visit ? "مكتملة" : "فعالة";
  return <span className={status === "draft" ? styles.badge : styles.active} aria-label={`${visit ? "حالة الزيارة" : "حالة بطاقة المريض"}: ${text}`}>{text}</span>;
}
function Listing({ facility }: { facility: number }) {
  const [chosenColumns,setColumns]=useState<(keyof typeof reportColumns)[]>(defaultColumns);
  const options = useClinicRequest<WizardOptions>(`dossiers/options?facility_id=${facility}`);
  const availableColumns = Object.fromEntries(Object.entries(reportColumns).filter(([key])=>options.data?.capabilities.treatment_view || !(key in treatmentColumns)));
  const columns = chosenColumns.filter(key=>key in availableColumns);
  const params = useSearchParams(); const pathname = usePathname();
  const { search, committed, change, cancel, searching } = useClinicSearch(pathname, params.toString(), facility);
  const q = new URLSearchParams({ facility_id: String(facility) });
  for (const key of ["treatment_status","treatment_modality","dose_from","dose_to","pathology_status", "status", "oncology", "visits", "from", "to", "sort", "direction", "page", "per_page"]) { const value = params.get(key); if (value) q.set(key, value); }
  if (committed) q.set("search", committed);
  const list = useClinicRequest<Page<DossierRow> & { totals: { dossiers: number } }>(`dossiers?${q}`, true, true);
  function filter(key: string, value: string) { cancel(); const next = new URLSearchParams(q); if (value) next.set(key, value); else next.delete(key); if (key !== "page") next.delete("page"); window.history.replaceState(null, "", `${pathname}?${next}`); }
  const exportQuery=new URLSearchParams(q);columns.forEach(c=>exportQuery.append("columns[]",c));
  const headings = [...columns.map(k=>reportColumns[k]),"الإجراءات"];
  return <><header className={styles.heading}><div><h2>بطاقات المرضى</h2><p>ملفات المرضى ومسوداتهم في المشفى</p></div><div>{options.data?.creation.allowed ? <Link className={styles.primary} href={`/patient-cards/new?${q}`}><LuPlus aria-hidden="true" />تسجيل بطاقة مريض</Link> : <button type="button" className={styles.primary} disabled aria-describedby="add-dossier-note"><LuPlus aria-hidden="true" />تسجيل بطاقة مريض</button>}<p id="add-dossier-note" className={styles.hint}>{options.data?.creation.allowed ? "احفظ البيانات على مراحل، وتابع المسودة لاحقًا." : options.loading ? "جارٍ التحقق من إمكانية الإضافة…" : options.error ? "تعذّر التحقق من إمكانية الإضافة؛ أعد المحاولة." : options.data?.creation.reason}</p>{options.error && <button className={styles.secondary} onClick={options.retry}>إعادة التحقق من إمكانية الإضافة</button>}</div></header>
    {options.data?.capabilities.import_view && <Link className={styles.secondary} href={`/patient-cards/imports?facility_id=${facility}`}>استيراد بطاقات المرضى من Excel</Link>}
    <section className={styles.panel}><div className={`${styles.toolbar} ${cardStyles.toolbar}`}><DossierReports path="dossiers/export" filters={exportQuery.toString()} ready={!!list.data&&!list.loading&&!list.error&&!searching} allowed={!!options.data?.capabilities.export}/><ColumnMenu<string> labels={availableColumns} visible={columns} onChange={next=>setColumns(next.filter((key):key is keyof typeof reportColumns=>key in availableColumns))}/><label className={styles.search}><span><LuSearch aria-hidden="true" />البحث</span><input type="search" aria-label="البحث في بطاقات المرضى" placeholder="كود المريض أو الاسم أو معرّف قديم…" value={search} onChange={e => change(e.target.value)} /></label></div><div className={styles.filters}>
      <label>حالة بطاقة المريض<select value={params.get("status") ?? "all"} onChange={e => filter("status", e.target.value)}><option value="all">الكل</option><option value="draft">مسودة</option><option value="active">فعالة</option></select></label>
      <label>بداية الملف الطبي في المشفى من<input type="date" value={params.get("from") ?? ""} onChange={e => filter("from", e.target.value)} /></label>
      <label>بداية الملف الطبي في المشفى إلى<input type="date" value={params.get("to") ?? ""} onChange={e => filter("to", e.target.value)} /></label>
      <label>حالة التشريح المرضي<select value={params.get("pathology_status")??""} onChange={e=>filter("pathology_status",e.target.value)}><option value="">الكل</option>{Object.entries(dispositionLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
      {options.data?.capabilities.treatment_view&&<><label>نمط العلاج<select value={params.get("treatment_modality")??""} onChange={e=>filter("treatment_modality",e.target.value)}><option value="">الكل</option>{Object.entries(modalities).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>{[["dose_from","مواعيد مؤهلة من"],["dose_to","مواعيد مؤهلة إلى"]].map(([key,label])=><label key={key}>{label}<input type="date" value={params.get(key)??""} onChange={e=>filter(key,e.target.value)}/></label>)}</>}<label>الحالة الورمية<select value={params.get("oncology") ?? ""} onChange={e => filter("oncology", e.target.value)}><option value="">الكل</option><option value="yes">ورمي</option><option value="no">غير ورمي</option></select></label>
      <label>الزيارات<select value={params.get("visits") ?? ""} onChange={e => filter("visits", e.target.value)}><option value="">الكل</option><option value="with">لديه زيارات</option><option value="without">دون زيارات</option></select></label>
      <label>الترتيب<select value={params.get("sort") ?? "opening_date"} onChange={e => filter("sort", e.target.value)}><option value="opening_date">بداية الملف الطبي في المشفى</option><option value="code">كود المريض</option><option value="patient_name">اسم المريض</option><option value="visit_count">عدد الزيارات</option></select></label>
      <label>الاتجاه<select value={params.get("direction") ?? "desc"} onChange={e => filter("direction", e.target.value)}><option value="desc">تنازلي</option><option value="asc">تصاعدي</option></select></label>
    </div>
    {(list.loading || searching) && <p className={styles.status} role="status">{list.data ? "جارٍ تحديث النتائج؛ تظهر النتائج السابقة مؤقتًا." : "جارٍ تحميل بطاقات المرضى…"}</p>}
    {list.error && <><Failure error={list.error} retry={list.retry} />{list.data && <p role="status">المعروض نتائج سابقة؛ أعد التحميل للحصول على النتائج الحالية.</p>}</>}
    {list.data && <><div className={styles.resultSummary}><strong>{list.data.totals.dossiers} بطاقة مريض مطابقة</strong></div>{list.data.data.length ? <DirectoryTable label="جدول بطاقات المرضى" busy={list.loading || searching} headers={headings}>{list.data.data.map((row, index) => <tr key={row.id}>{columns.map(key=><td key={key} className={["sequence","code","visit_count","procedure_count","latest_visit_date","opening_date","birth_date","phone","paper_file_number","gender"].includes(key)?styles.identifierCell:undefined}>{key==="sequence"?(list.data!.meta.page-1)*list.data!.meta.per_page+index+1:key==="code"?<><bdi>{row.code}</bdi>{row.legacy_without_visits&&<small className={styles.hint}>سجل قديم بلا زيارة مرتبطة؛ يحتاج مراجعة.</small>}</>:key==="name"?row.patient_name:key==="diagnoses"?<>{row.latest_visit_status&&<StatusBadge status={row.latest_visit_status} visit/>}<LongText text={row.diagnoses.map(d=>d.name).join(" · ")}/></>:key==="clinics"?[...new Set(row.diagnoses.map(d=>d.clinic).filter(Boolean))].join(" · ")||"غير مسجلة":key==="doctors"?[...new Set(row.diagnoses.map(d=>d.doctor).filter(Boolean))].join(" · ")||"غير مسجل":key==="pathology_status"?dispositionLabels[row.pathology_status]:key==="treatment_modalities"?row.treatment_modalities?.split(",").map(code=>modalities[code]??code).join(" · ")||"غير مسجل":key==="status"?<StatusBadge status={row.status}/>:key==="gender"?valueLabels[row.gender]??"غير معروف":key==="birth_date"?patientBirthDate(row.birth_date,row.birth_date_accuracy):key==="is_oncology"?<span className={row.is_oncology?styles.active:styles.badge}>{row.is_oncology?"ورمي":"غير ورمي"}</span>:row[key]??"غير مسجل"}</td>)}<td><DirectoryRowActions name={row.code} href={`/patient-cards/${row.id}?${q}`} >{row.workflow.resume_section !== null && <Link className={styles.textButton} href={`/patient-cards/new?card=${row.id}&${q}&section=${row.workflow.resume_section}`}>{row.status === "draft" ? "استكمال بيانات البطاقة" : "تعديل البيانات"}</Link>}{row.workflow.subsequent_create&&<Link className={styles.textButton} href={`/patient-cards/new?card=${row.id}&${q}&visit=new`}>إضافة زيارة للمريض</Link>}</DirectoryRowActions></td></tr>)}</DirectoryTable> : <div className={styles.status}>لا توجد بطاقات مرضى مطابقة.</div>}<Pagination meta={list.data.meta} onPage={p => filter("page", String(p))} onPageSize={s => filter("per_page", s)} /></>}
    </section></>;
}
const personalLabels: Record<string, string> = { first_name: "الاسم الأول", family_name: "اسم العائلة", father_name: "اسم الأب", mother_name: "اسم الأم", birth_date: "تاريخ الميلاد", birth_date_accuracy: "دقة الميلاد", gender: "الجنس", phone: "الهاتف", paper_file_number: "رقم الملف الورقي", alt_phone: "هاتف بديل", governorate: "المحافظة", city: "المدينة", address_line: "عنوان السكن", displacement_status: "حالة النزوح" };
const valueLabels: Record<string, string> = { unknown: "غير معروف", male: "ذكر", female: "أنثى", exact: "دقيق", year_only: "السنة فقط", estimated: "تقديري", resident: "مقيم", idp: "نازح" };
function Detail({ id, facility }: { id: string; facility: number }) {
  const revision=0;
  const params = useSearchParams(); const router = useRouter(); const pathname = usePathname();
  const back = new URLSearchParams(params.toString()); back.set("facility_id", String(facility)); back.delete("visit"); back.delete("visits_page");
  const options=useClinicRequest<WizardOptions>(`dossiers/options?facility_id=${facility}`);
  const record = useClinicRequest<Dossier>(`dossiers/${id}?facility_id=${facility}`,false,true,revision);
  const visitId = params.get("visit"); const validVisit = visitId && /^[1-9]\d*$/.test(visitId);
  const hq=new URLSearchParams({facility_id:String(facility),per_page:"10"});for(const key of ["page","per_page","search","from","to","status","sort","direction"]){const v=params.get(`visits_${key}`);if(v)hq.set(key,v);}
  const history = useClinicRequest<Page<Pick<Visit, "id" | "visit_no" | "visit_date" | "status">>>(`dossiers/${id}/visits?${hq}`, true);
  const prior = useClinicRequest<Visit>(validVisit ? `dossiers/${id}/visits/${visitId}?facility_id=${facility}` : null,false,true,revision);
  function navigate(key: string, value: string) { const next = new URLSearchParams(params.toString()); next.set("facility_id", String(facility)); if (value) next.set(key, value); else next.delete(key); router.push(`${pathname}?${next}`, { scroll: false }); }
  function filterHistory(key:string,value:string){const next=new URLSearchParams(params.toString());if(value)next.set(`visits_${key}`,value);else next.delete(`visits_${key}`);if(key!=="page")next.delete("visits_page");window.history.replaceState(null,"",`${pathname}?${next}`);}
  const d = record.data; const selected = visitId ? prior.data : d?.latest_visit;
  return <><DirectoryBack href={`/patient-cards?${back}`}>العودة إلى بطاقات المرضى</DirectoryBack>{record.loading && <p role="status">جارٍ تحميل بطاقة المريض…</p>}{record.error && <Failure error={record.error} retry={record.retry} />}{d && <>
    <header className={styles.heading}><div><h2>بطاقة المريض <bdi>{d.code}</bdi></h2><StatusBadge status={d.status} /><p>{d.patient.first_name} {d.patient.family_name} · بداية الملف الطبي في المشفى {d.opening_date}</p></div><span className={styles.active}>{d.visit_count} زيارة</span></header>
    {d.legacy_without_visits&&<p role="status">سجل قديم بلا زيارة مرتبطة. لم تُنشأ زيارة لتسوية البيانات؛ يسجّل الموظف زيارة فعلية فقط.</p>}
    <div className={styles.actions}>{<>
      {d.status === "draft" && d.workflow.resume_section !== null && <Link className={styles.primary} href={`/patient-cards/new?card=${id}&${back}&section=${d.workflow.resume_section}`}>استكمال بيانات البطاقة</Link>}
      {d.workflow.personal_update && <Link className={styles.secondary} href={`/patient-cards/new?card=${id}&${back}&section=0`}>تعديل البيانات الشخصية</Link>}
      {d.workflow.medical_update && <Link className={styles.secondary} href={`/patient-cards/new?card=${id}&${back}&section=1`}>تعديل المعلومات الطبية</Link>}
      {d.workflow.visit.action && <Link className={styles.secondary} href={`/patient-cards/new?card=${id}&${back}&section=2`}>{d.workflow.visit.label}</Link>}
      {d.workflow.subsequent_create&&<Link className={styles.primary} href={`/patient-cards/new?card=${id}&${back}&visit=new`}>إضافة زيارة للمريض</Link>}
      {options.data?.capabilities.audit ? <a className={styles.secondary} href="#dossier-change-history">سجل التغييرات</a> : <button className={styles.secondary} disabled title="يتطلب عرض سجل التغييرات صلاحية مستقلة">سجل التغييرات</button>}
    </>}</div>
    <section className={styles.detailPanel}><h2>بيانات المريض الحالية</h2><dl className={styles.facts}>{Object.entries(personalLabels).map(([key, label]) => <div key={key}><dt>{label}</dt><dd>{key === "birth_date" ? patientBirthDate(d.patient.birth_date, d.patient.birth_date_accuracy) : valueLabels[d.patient[key] ?? ""] ?? d.patient[key] ?? "غير مسجل"}</dd></div>)}</dl></section>
    <section className={styles.detailPanel}><h2>ملخص الحالة الطبية الحالية</h2><dl className={styles.facts}><div><dt>الإعاقات</dt><dd><LongText text={d.disability_text} /></dd></div><div><dt>القصة المرضية المختصرة</dt><dd><LongText text={d.clinical_history} /></dd></div><div><dt>مريض ورمي</dt><dd>{d.is_oncology ? "نعم" : "لا"}</dd></div></dl>{d.oncology && <><h3>الملف الورمي الحالي</h3><dl className={styles.facts}><div><dt>أنواع السوابق</dt><dd>{d.oncology.selections.filter(s => s.selection_group === "history").map(s => historyLabels[s.code]).join(" · ") || "غير مسجلة"}</dd></div><div><dt>العلاجات السابقة</dt><dd>{d.oncology.selections.filter(s => s.selection_group === "treatment").map(s => treatmentLabels[s.code]).join(" · ") || "غير مسجلة"}</dd></div><div><dt>الفحوص السابقة</dt><dd><LongText text={d.oncology.previous_examinations} /></dd></div><div><dt>مصدر الدواء العام</dt><dd>{sourceLabels[d.oncology.medication_source ?? ""] ?? "غير مسجل"}{d.oncology.other_organization && ` · ${d.oncology.other_organization}`}</dd></div></dl></>}</section>
    <PathologyPanel facility={facility} dossier={Number(id)} caps={{attachments_download:!!options.data?.capabilities.attachments_download}} onChanged={()=>{}}/><OncologyPanel facility={facility} dossier={Number(id)} caps={{treatment_view:!!options.data?.capabilities.treatment_view}} revision={revision} onChanged={()=>{}}/>
    <section className={styles.detailPanel}><h2>حالة التشريح المرضي</h2><p>{dispositionLabels[d.pathology_summary?.disposition??"not_assessed"]}</p><p className={styles.hint}>تُحسب الحالة من أحدث واقعة طبية غير ملغاة؛ كل تقرير يعرض زيارته المصدر.</p></section><Link className={styles.secondary} href={`/patient-cards/new?facility_id=${facility}&card=${id}&section=6`}>التقييم والتشريح المرضي في مساحة العمل</Link>{options.data?.capabilities.treatment_view&&<Link className={styles.secondary} href={`/patient-cards/new?facility_id=${facility}&card=${id}&section=7`}>الخطة ومواعيد العلاج في مساحة العمل</Link>}<section className={styles.panel}><div className={styles.toolbar}><h2>سجل الزيارات</h2><p>حسب التاريخ الفعلي، ثم معرّف الزيارة عند تساوي التاريخ.</p></div><div className={styles.filters}>{[["search","البحث بكود الزيارة","search"],["from","تاريخ الزيارة من","date"],["to","تاريخ الزيارة إلى","date"]].map(([key,label,type])=><label key={key}>{label}<input type={type} value={params.get(`visits_${key}`)??""} onChange={e=>filterHistory(key,e.target.value)}/></label>)}<label>حالة الزيارة<select value={params.get("visits_status")??"all"} onChange={e=>filterHistory("status",e.target.value)}><option value="all">الكل</option><option value="draft">مسودة</option><option value="complete">مكتملة</option></select></label><label>ترتيب الزيارات<select value={params.get("visits_sort")??"visit_date"} onChange={e=>filterHistory("sort",e.target.value)}><option value="visit_date">التاريخ الفعلي</option><option value="visit_no">كود الزيارة</option><option value="status">الحالة</option></select></label><label>اتجاه الزيارات<select value={params.get("visits_direction")??"desc"} onChange={e=>filterHistory("direction",e.target.value)}><option value="desc">تنازلي</option><option value="asc">تصاعدي</option></select></label></div>{history.loading && <p role="status">جارٍ تحميل الزيارات…</p>}{history.error && <Failure error={history.error} retry={history.retry} />}{history.data && <><DirectoryTable label="زيارات بطاقة المريض" headers={["رقم الزيارة", "التاريخ الفعلي", "الاستعراض"]}>{history.data.data.map(v => <tr key={v.id}><td><bdi>{v.visit_no}</bdi><div><StatusBadge status={v.status} visit /></div></td><td>{v.visit_date}</td><td><button className={styles.secondary} onClick={() => navigate("visit", String(v.id))}>{v.id === d.latest_visit?.id ? "استعراض آخر زيارة" : "استعراض الزيارة"}</button></td></tr>)}{!history.data.data.length && <tr><td colSpan={3}>لا توجد زيارات مسجلة لبطاقة المريض.</td></tr>}</DirectoryTable><Pagination meta={history.data.meta} onPage={p=>filterHistory("page",String(p))} onPageSize={v=>filterHistory("per_page",v)} /></>}</section>
    <section className={styles.panel}><div className={styles.toolbar}><h2>{visitId ? "الزيارة المختارة" : "آخر زيارة فعلية"}</h2>{visitId && <button className={styles.secondary} onClick={() => navigate("visit", "")}>العودة إلى آخر زيارة</button>}</div>
      {visitId && !validVisit ? <p role="alert">مرجع الزيارة غير صالح.</p> : prior.loading && !prior.data ? <p role="status">جارٍ تحميل الزيارة…</p> : prior.error && !prior.data ? <Failure error={prior.error} retry={prior.retry} /> : selected ? <><div className={styles.toolbar}><DossierReports key={selected.id} path={`dossiers/${id}/visits/${selected.id}/report`} filters={`facility_id=${facility}`} ready={!prior.loading&&!prior.error} allowed={!!options.data?.capabilities.export}/>{selected.status==="draft"&&options.data?.capabilities.visits_update&&<Link className={styles.secondary} href={`/patient-cards/new?card=${id}&${back}&visit=${selected.id}&section=2`}>استكمال هذه الزيارة المسودة</Link>}</div><VisitSummary visit={selected}/><OncologyPanel facility={facility} dossier={Number(id)} visit={selected} caps={{treatment_view:!!options.data?.capabilities.treatment_view}} revision={revision} onChanged={()=>{}}/>{options.data?.capabilities.treatment_view&&<Link className={styles.secondary} href={`/patient-cards/new?facility_id=${facility}&card=${id}&visit=${selected.id}&section=8`}>تسجيل الجرعات في مساحة العمل</Link>}{options.data?.capabilities.treatment_view&&<Link className={styles.secondary} href={`/patient-cards/new?facility_id=${facility}&card=${id}&visit=${selected.id}&section=4`}>أدوية الزيارة في مساحة العمل</Link>}<Link className={styles.secondary} href={`/patient-cards/new?facility_id=${facility}&card=${id}&visit=${selected.id}&section=6`}>التقييم والتشريح المرضي في مساحة العمل</Link><AttachmentHistory key={selected.id} facility={facility} dossier={d.id} visit={selected.id} caps={options.data?.capabilities??{}}/></> : <p className={styles.status}>لا توجد زيارات فعلية مرتبطة ببطاقة المريض هذه.</p>}
    </section>
    {options.data?.capabilities.export && <DossierHistoryReport dossier={id} facility={facility} ready={!!d&&!record.loading&&!record.error} />}
    {options.data?.capabilities.audit && <DossierAuditHistory dossier={id} facility={facility} attachments={!!options.data?.capabilities.attachments_view} />}
  </>}</>;
}
function ClinicalTable({ title, items, draft }: { title: string; items: ClinicalItem[]; draft: boolean }) {
  return <><h3>{title}</h3>{draft && !items.length ? <p className={styles.hint}>لم تُسجّل بيانات هذا القسم بعد.</p> : <DirectoryTable label={title} headers={["الاسم", "التاريخ", "التفاصيل"]}>{items.map(item => <tr key={item.id}><td>{item.name}</td><td>{item.date}</td><td>{item.dose_text || ""} {item.quantity != null ? `${item.quantity} ${item.quantity_unit ?? ""}` : "—"}</td></tr>)}{!items.length && <tr><td colSpan={3}>لا توجد بيانات مسجلة.</td></tr>}</DirectoryTable>}</>;
}
function VisitSummary({ visit: v }: { visit: Visit }) {
  const draft = v.status === "draft";
  return <div className={styles.detailPanel}><h3>زيارة <bdi>{v.visit_no}</bdi> · {v.visit_date}</h3><StatusBadge status={v.status} visit />
    {draft && <p className={styles.hint}>هذه زيارة مسودة؛ المعروض هو البيانات المحفوظة حتى الآن، وقد تُستكمل أقسامها لاحقًا.</p>}
    {!!v.is_referred && <dl className={styles.facts}><div><dt>المشفى المحيل</dt><dd>{v.referring_hospital}</dd></div><div><dt>تاريخ الإحالة</dt><dd>{v.referral_date}</dd></div><div><dt>سبب الإحالة</dt><dd><LongText text={v.referral_reason ?? null} /></dd></div></dl>}
    {(v.visit_clinic || v.attending_doctor) && <p className={styles.hint}>سياق الزيارة المسجل: {v.visit_clinic ?? "عيادة غير مسجلة"} · {v.attending_doctor ?? "طبيب غير مسجل"}. لا يُنسب تلقائيًا إلى كل تشخيص.</p>}
    {draft && !v.diagnoses.length ? <p className={styles.hint}>لم تُسجّل تشخيصات لهذه المسودة بعد.</p> : <DirectoryTable label="تشخيصات الزيارة" headers={["التشخيص", "تاريخ التشخيص", "العيادة", "الطبيب المسؤول"]}>{v.diagnoses.map(d => <tr key={d.id}><td>{d.name} <bdi>({d.code})</bdi></td><td>{d.diagnosed_on ?? "غير معروف"}</td><td>{d.clinic ?? "غير مسجلة"}</td><td>{d.doctor ?? "غير مسجل"}</td></tr>)}{!v.diagnoses.length && <tr><td colSpan={4}>لا توجد تشخيصات مسجلة.</td></tr>}</DirectoryTable>}
    {v.clinical?.prescription&&<section><h3>الوصفة الطبية — لا تمثل صرفًا</h3><p>{v.clinical.prescription.prescribed_on} · {v.clinical.prescription.clinic_name} · {v.clinical.prescription.doctor_name}</p><LongText text={v.clinical.prescription.note}/><DirectoryTable label="أدوية الوصفة" headers={["الدواء المحفوظ","الملاحظة"]}>{v.clinical.prescription.items.map(i=><tr key={i.id}><td><bdi>{i.code}</bdi> · {i.name_ar}</td><td><LongText text={i.note}/></td></tr>)}</DirectoryTable></section>}
    {v.clinical?.outcome&&<section><h3>نتيجة الزيارة وسياقها</h3><p>{v.clinical.outcome.name_ar} · {v.clinical.outcome.outcome_on} · {v.clinical.outcome.clinic_name} · {v.clinical.outcome.doctor_name}</p><LongText text={v.clinical.outcome.note}/>{v.clinical.outcome.code==="DOS-REFER"&&<p>الإحالة الصادرة: {v.clinical.outcome.referral_target} · {v.clinical.outcome.outgoing_referral_date} · {v.clinical.outcome.outgoing_referral_reason}</p>}</section>}
    {v.clinical?(["services","procedures"] as const).map(kind=><section key={kind}><h3>{kind==="services"?"الخدمات المسجلة":"الإجراءات المسجلة"}</h3><DirectoryTable label={kind==="services"?"الخدمات المسجلة":"الإجراءات المسجلة"} headers={["البيان","التاريخ","العيادة","الطبيب","الكمية","الملاحظة"]}>{v.clinical?.[kind].map(row=><tr key={row.id}><td>{row.name_ar}</td><td>{row.performed_on}</td><td>{row.clinic_name??"غير مسجلة"}</td><td>{row.doctor_name??"غير مسجل"}</td><td>{row.quantity}</td><td><LongText text={row.note}/></td></tr>)}{!v.clinical?.[kind].length&&<tr><td colSpan={6}>{draft?"لم تُسجّل بيانات هذا القسم بعد.":"لا توجد بيانات مسجلة."}</td></tr>}</DirectoryTable></section>):<><ClinicalTable title="الخدمات المسجلة" items={v.services} draft={draft}/><ClinicalTable title="الإجراءات المسجلة" items={v.procedures} draft={draft}/></>}<ClinicalTable title="صرف غير مرتبط بالجرعة" items={v.medications.filter(item=>item.dispensing_purpose==="unlinked"||(!item.dispensing_purpose&&!item.dose_session_id))} draft={draft} /><ClinicalTable title="صرف خارج المشفى" items={v.medications.filter(item=>item.dispensing_purpose==="take_home")} draft={draft} /><ClinicalTable title="أدوية مرتبطة بالجرعة" items={[...v.administered_medications,...v.medications.filter(item=>item.dispensing_purpose==="supportive")]} draft={draft} /><ClinicalTable title="النتائج المسجلة" items={v.outcomes} draft={draft} />
  </div>;
}
