"use client";
import {useEffect,useRef,useState} from "react";
import {apiRequest,AuthError,subscribeSession} from "../auth/api";
import {useClinicRequest} from "../clinics/api";
import Modal from "../clinics/Modal";
import Picker from "./DossierPicker";
import {ClinicalContext} from "./ClinicalEditor";
import type {Context} from "./clinical";
import type {Visit} from "./api";
import {intents,modalities,planStates,sessionStates,type Dose,type Dispensing,type Plan,type Session,type TreatmentItem,type TreatmentOptions,type Values,type EditorKind} from "./oncology";
import styles from "../clinics/clinics.module.css";
import layout from "./wizard.module.css";
import oncology from "./oncology.module.css";

type Props={caps:Record<string,boolean>;kind:EditorKind;facility:number;dossier:number;plan?:Plan;session?:Session;visit?:Visit;dose?:Dose;dispensing?:Dispensing;onClose:()=>void;onSaved:()=>void;onRefresh:()=>void};
const titles:Record<EditorKind,string>={appointment:"موعد الجرعة القادمة",plan:"الخطة العلاجية",status:"مراجعة حالة الخطة",schedule:"جدولة جلسات العلاج",session:"تغيير الموعد المجدول",dose:"تسجيل إعطاء جرعة",dispense:"الأدوية المصروفة مع الجرعة","void-dose":"إبطال واقعة إعطاء","void-dispense":"إبطال واقعة صرف"};
const labels:Record<string,string>={session_resolution:"معالجة الموعد بعد إبطال الإعطاء",carry_forward:"نقل الموعد صراحة إلى النسخة الحالية",duplicate_reason:"سبب إنشاء خطة مطابقة مقصودة",protocol_name:"البروتوكول (الاسم أو الكود)",protocol_code:"الكود السابق",modality:"نمط العلاج",intent:"النية العلاجية",starts_on:"بداية مخططة",ends_on:"نهاية مخططة",planned_cycles:"عدد الدورات",planned_sessions:"عدد الجلسات",interval_days:"الفاصل بالأيام",clinic_id:"العيادة",doctor_id:"الطبيب الذي وضع الخطة",diagnosis_id:"التشخيص",note:"ملاحظة",amendment_reason:"سبب تعديل الخطة",status:"الحالة المطلوبة",reason:"سبب الإجراء أو التصحيح",override_reason:"مبرر استثناء عدم الحاجة للتشريح",planned_on:"الموعد الجديد",administered_on:"تاريخ الإعطاء الفعلي",dispensed_on:"تاريخ الصرف الفعلي",supervising_staff_id:"الطبيب المشرف",administered_by:"القائم بالإعطاء",prescribing_staff_id:"الطبيب المسؤول عن الصرف",reporting_period_id:"فترة التقرير للواقعة الفعلية",session_label:"عنوان جلسة الإعطاء",dispensing_purpose:"غرض الصرف",medication_name_snapshot:"اسم الدواء التاريخي إن لم يكن في الدليل",medication_code_snapshot:"كود الدواء التاريخي",dose_value:"قيمة الجرعة",dose_unit:"وحدة الجرعة",route:"طريق الإعطاء",instructions:"تعليمات الجدولة",dose_text:"تعليمات الجرعة",quantity:"الكمية",quantity_unit:"وحدة الكمية",funding_source_id:"مصدر التمويل"};
const planKeys=["protocol_name","modality","intent","starts_on","ends_on","planned_cycles","planned_sessions","interval_days","clinic_id","doctor_id","diagnosis_id","note","amendment_reason"];
const doseKeys=["administered_on","supervising_staff_id","administered_by","reporting_period_id","session_label","note","reason"];
const dispenseKeys=["dispensed_on","prescribing_staff_id","reporting_period_id","dispensing_purpose","medication_id","medication_name_snapshot","medication_code_snapshot","funding_source_id","dose_text","quantity","quantity_unit","note","reason"];
function subset(source:object|undefined,keys:string[]):Values {const s=source as Values|undefined;return Object.fromEntries(keys.map(k=>[k,s?.[k]??(k==="carry_forward"?false:"")]));}
export default function OncologyEditor(p:Props){
 const {kind,facility,dossier,plan,session,visit,dose,dispensing,onClose,onSaved,onRefresh}=p;
 const isVoid=kind.startsWith("void"),actual=kind==="dose"||kind==="dispense";
 const keys=kind==="appointment"?["planned_on","clinic_id","doctor_id","note"]:kind==="plan"?planKeys:kind==="dose"?doseKeys:kind==="dispense"?dispenseKeys:kind==="status"?["status","reason","override_reason"]:kind==="session"?["status","planned_on","reason","carry_forward"]:kind==="void-dose"?["reason","session_resolution","planned_on","carry_forward"]:["reason"];
 const original=kind==="void-dose"?dose:kind==="plan"?plan?.revisions[0]:kind==="dose"?dose:kind==="dispense"?dispensing:session;
 const [draft,setDraft]=useState<Values>(()=>({...subset(original,keys),carry_forward:false,...!original?{starts_on:"",status:"",...visit?{administered_on:visit.visit_date,dispensed_on:visit.visit_date}:{} }: {}}));
 const [items,setItems]=useState<TreatmentItem[]>(()=>kind==="plan"?plan?.revisions[0]?.items??[]:dose?.items??[]);
 const [sessions,setSessions]=useState<Values[]>([{planned_on:"",session_number:"",cycle_number:"",note:""}]);
 const [version,setVersion]=useState(plan?.lock_version??dose?.lock_version??dispensing?.lock_version??session?.lock_version??1);
 const [context,setContext]=useState<Context>({clinic:draft.clinic_id?{id:Number(draft.clinic_id),name_ar:String(plan?.revisions[0]?.clinic_name??"العيادة المحفوظة")}:null,doctor:draft.doctor_id?{id:Number(draft.doctor_id),name_ar:String(plan?.revisions[0]?.doctor_name??"الطبيب المحفوظ")}:null});
 const [attendance,setAttendance]=useState({session_lock_version:session?.lock_version??dose?.session_lock_version,plan_lock_version:plan?.lock_version??session?.plan_lock_version??dose?.plan_lock_version,visit_lock_version:visit?.lock_version});
 const [obsolete,setObsolete]=useState(kind==="session"?session?.revision_id!==session?.current_revision_id:kind==="void-dose"?dose?.session_revision_id!==dose?.current_revision_id:false);
 const [duplicate,setDuplicate]=useState(false);
 const [busy,setBusy]=useState(false),[error,setError]=useState<AuthError|null>(null),[conflict,setConflict]=useState(false),[latest,setLatest]=useState<{values:Values;version:number;items:TreatmentItem[];closed:boolean;obsolete:boolean;attendance?:typeof attendance}|null>(null),[choices,setChoices]=useState<Record<string,boolean>>({});
 const pending=useRef<AbortController|null>(null),reservation=useRef<{body:string;id:string}|null>(null),form=useRef<HTMLFormElement>(null),close=useRef(onClose);
 useEffect(()=>{close.current=onClose;},[onClose]);
 useEffect(()=>{const unsubscribe=subscribeSession(()=>{pending.current?.abort();close.current();});return()=>{unsubscribe();pending.current?.abort();};},[]);
 useEffect(()=>{if(busy||conflict||error?.status!==422)return;const key=Object.keys(error.fields??{})[0];const field=Array.from(form.current?.querySelectorAll<HTMLElement>("[name]")??[]).find(x=>x.getAttribute("name")===key);field?.focus();field?.scrollIntoView({block:"center"});},[busy,conflict,error]);
 const optionDate=String(actual?visit?.visit_date:draft.planned_on||draft.starts_on||plan?.revisions[0]?.starts_on||"2000-01-01");
 const options=useClinicRequest<TreatmentOptions>(`dossiers/treatment-options?facility_id=${facility}&date=${optionDate}${(session?.clinic_id??dose?.clinic_id??dispensing?.clinic_id)?`&clinic_id=${session?.clinic_id??dose?.clinic_id??dispensing?.clinic_id}`:""}`);
 const base=`dossiers/${dossier}`,planPath=`${base}/treatment-plans${plan?`/${plan.id}`:""}`,dosePath=`${base}/visits/${visit?.id}/doses`,dispensePath=`${base}/visits/${visit?.id}/dispensing`;
 const path=kind==="appointment"?`${base}/treatment-sessions`:kind==="plan"?planPath:kind==="status"?`${planPath}/status`:kind==="schedule"?`${planPath}/sessions`:kind==="session"?`${base}/treatment-sessions/${session?.id}`:kind==="dose"?`${dosePath}${dose?`/${dose.id}`:""}`:kind==="dispense"?`${dispensePath}${dispensing?`/${dispensing.id}`:""}`:kind==="void-dose"?`${dosePath}/${dose?.id}/void`:`${dispensePath}/${dispensing?.id}/void`;
 function resolutionDraft(values:Values,isObsolete=obsolete):Values {const status=kind==="void-dose"?values.session_resolution:values.status;return kind==="session"||kind==="void-dose"?{...values,carry_forward:!!values.carry_forward&&isObsolete&&status==="rescheduled"}:values;}
 const update=(key:string,value:string|number|boolean|null)=>setDraft(d=>resolutionDraft({...d,[key]:value}));
 const fieldError=(key:string)=>error?.fields[key]?<small id={`error-${key}`} className={styles.fieldError} role="alert">{error.fields[key]}</small>:null;
 function field(key:string,opts?:Record<string,string>,value=draft,set:(key:string,value:string|number|null)=>void=update,prefix=""){const name=prefix+key;const date=key.endsWith("_on"),numeric=["planned_cycles","planned_sessions","interval_days","dose_value","quantity"].includes(key);return <label key={name}>{labels[key]??key}{opts?<select name={name} value={String(value[key]??"")} onChange={e=>set(key,e.target.value)} aria-invalid={!!error?.fields[name]} aria-describedby={error?.fields[name]?`error-${name}`:undefined}><option value="">اختر…</option>{Object.entries(opts).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select>:<input name={name} required={key==="planned_on"&&(kind==="session"||kind==="void-dose")} type={date?"date":numeric?"number":"text"} step={numeric?"any":undefined} value={String(value[key]??"")} onChange={e=>set(key,e.target.value)} aria-invalid={!!error?.fields[name]} aria-describedby={error?.fields[name]?`error-${name}`:undefined}/>} {fieldError(name)}</label>;}
 async function refresh(){if(pending.current)return;const c=new AbortController();pending.current=c;setBusy(true);setError(null);try{let values:Values,items:TreatmentItem[]=[],version:number,closed=false;let freshAttendance:typeof attendance|undefined;let freshObsolete=obsolete;
  if(plan){const current=await apiRequest<Plan>(`${base}/treatment-plans/${plan.id}?facility_id=${facility}`,{signal:c.signal});values=kind==="plan"?subset(current.revisions[0],keys):{...draft,status:current.effective_status};items=current.revisions[0].items;version=current.lock_version;closed=["completed","cancelled"].includes(current.effective_status);if(kind==="dose"){const scheduled=await apiRequest<Session>(`${base}/treatment-sessions/${session!.id}?facility_id=${facility}`,{signal:c.signal});const currentVisit=await apiRequest<Visit>(`${base}/visits/${visit!.id}?facility_id=${facility}`,{signal:c.signal});freshAttendance={plan_lock_version:current.lock_version,session_lock_version:scheduled.lock_version,visit_lock_version:currentVisit.lock_version};closed=current.effective_status!=="active"||scheduled.revision_id!==current.current_revision_id||scheduled.planned_on!==visit!.visit_date||!["scheduled","rescheduled"].includes(scheduled.status);values={...draft};}}
  else if(kind==="session"){const current=await apiRequest<Session>(`${base}/treatment-sessions/${session!.id}?facility_id=${facility}`,{signal:c.signal});values=subset(current,keys);version=current.lock_version;closed=current.status==="completed";freshAttendance={...attendance,plan_lock_version:current.plan_lock_version??undefined,session_lock_version:current.lock_version};freshObsolete=current.revision_id!==current.current_revision_id;}
  else {const current=await apiRequest<{doses:Dose[];dispensed:Dispensing[]}>(`${dosePath}?facility_id=${facility}`,{signal:c.signal});const row=kind.includes("dispens")?current.dispensed.find(x=>x.id===dispensing?.id):current.doses.find(x=>x.id===dose?.id);if(!row)throw new Error("تعذّر العثور على السجل الحالي؛ أعد فتحه بعد مراجعة القائمة.");values=subset(row,keys);items=(row as Dose).items??[];version=row.lock_version;closed=!!row.voided_at;if(kind==="void-dose"){freshAttendance={...attendance,session_lock_version:(row as Dose).session_lock_version,plan_lock_version:(row as Dose).plan_lock_version};freshObsolete=(row as Dose).session_revision_id!==(row as Dose).current_revision_id;}}
  if(!c.signal.aborted){setLatest({values,items,version,closed,obsolete:freshObsolete,attendance:freshAttendance});setChoices({});onRefresh();}
 }catch(e){if(!c.signal.aborted)setError(e as AuthError);}finally{if(pending.current===c)pending.current=null;if(!c.signal.aborted)setBusy(false);}}
 function review(){if(!latest||latest.closed)return;const values={...latest.values};for(const key of keys)if(choices[key])values[key]=draft[key];setDraft(resolutionDraft(values,latest.obsolete));if(kind==="plan"||kind==="dose"&&dose){if(!choices.items)setItems(latest.items);else if(kind==="dose")setItems(xs=>xs.map(x=>{const current=latest.items.find(i=>i.id===x.id);return current?{...x,lock_version:current.lock_version}:x;}));}if(latest.attendance)setAttendance(latest.attendance);setVersion(latest.version);setObsolete(latest.obsolete);setContext({clinic:values.clinic_id?{id:Number(values.clinic_id),name_ar:"العيادة المختارة بعد المراجعة"}:null,doctor:values.doctor_id?{id:Number(values.doctor_id),name_ar:"الطبيب المختار بعد المراجعة"}:null});setLatest(null);setConflict(false);setError(null);}
 async function save(){if(pending.current||conflict)return;const c=new AbortController();pending.current=c;setBusy(true);setError(null);
  const clean=(v:Values)=>Object.fromEntries(Object.entries(v).filter(([k])=>k!=="key").map(([k,v])=>[k,v===""?null:v]));
  const payload={...clean(resolutionDraft(draft)),facility_id:facility,lock_version:version,...kind==="plan"?(!plan?{items:[]}:{}):kind==="dose"?{items:items.map(clean)}:{},...kind==="schedule"?{sessions:sessions.map(clean)}:{},...kind==="dose"&&!dose?{session_id:session?.id,...attendance}:{},...kind==="session"||kind==="void-dose"?{plan_lock_version:attendance.plan_lock_version,...kind==="void-dose"?{session_lock_version:attendance.session_lock_version}:{}}:{},...kind==="dispense"?{dose_session_id:dispensing?.dose_session_id??dose?.id}:{} };
  const body=JSON.stringify(payload);if(reservation.current?.body!==body)reservation.current={body,id:crypto.randomUUID()};
  try{await apiRequest(path,{method:kind==="session"||(kind==="plan"&&plan)||(kind==="dose"&&dose)||(kind==="dispense"&&dispensing)?"PUT":"POST",signal:c.signal,body:JSON.stringify({...payload,request_id:reservation.current.id})});if(!c.signal.aborted)onSaved();}
  catch(e){if(!c.signal.aborted){const failure=e as AuthError;setError(failure);if(failure.code==="ONCOLOGY_DUPLICATE_PLAN")setDuplicate(true);else if(failure.status===409)setConflict(true);}}
  finally{if(pending.current===c)pending.current=null;if(!c.signal.aborted)setBusy(false);}}
 const doctors=Object.fromEntries(options.data?.doctors.map(x=>[x.id,x.name_ar])??[]);
 const funding=Object.fromEntries(options.data?.funding_sources.map(x=>[x.id,x.name_ar])??[]),staff=Object.fromEntries(options.data?.staff.map(x=>[x.id,x.name_ar])??[]),periods=Object.fromEntries(options.data?.periods.map(x=>[x.id,`${x.starts_on} — ${x.ends_on}`])??[]);
 function medication(item:TreatmentItem,i:number,change:(key:string,value:string|number|null)=>void,prefix:string){return <><div><Picker name={`${prefix}medication_id`} label={`الدواء من الدليل ${i+1}`} path={`dossiers/options/medications?facility_id=${facility}`} selected={item.medication_id?{id:Number(item.medication_id),name_ar:String(item.medication_name_snapshot||"الدواء المحفوظ")}:null} onSelect={v=>{change("medication_id",v.id);change("medication_name_snapshot",v.name_ar);change("medication_code_snapshot",v.code??null);}}/>{fieldError(`${prefix}medication_id`)}</div>{!item.medication_id&&<>{field("medication_name_snapshot",undefined,item,change,prefix)}{field("medication_code_snapshot",undefined,item,change,prefix)}</>}{kind!=="dispense"&&<>{field("dose_value",undefined,item,change,prefix)}{field("dose_unit",undefined,item,change,prefix)}{field("route",undefined,item,change,prefix)}</>}{kind==="plan"?field("instructions",undefined,item,change,prefix):<>{field("quantity",undefined,item,change,prefix)}{field("quantity_unit",undefined,item,change,prefix)}{field("dose_text",undefined,item,change,prefix)}</>}{field("funding_source_id",funding,item,change,prefix)}{field("note",undefined,item,change,prefix)}</>;}
 return <Modal title={titles[kind]} size="wide" busy={busy} onClose={onClose}><form className={`${styles.form} ${layout.editorForm}`} ref={form} noValidate onSubmit={e=>{e.preventDefault();void save();}}><p className={styles.hint}>{actual?`الزيارة ${visit?.visit_no} · ${visit?.visit_date}. سجّل ما أُجري فعلًا فقط؛ لا حركة مخزون ولا صرف تلقائي.`:"الخطة والموعد لا ينشئان زيارة أو إعطاءً أو صرفًا. كل تغيير يُحفظ بعد تأكيدك فقط."}</p>{error&&<p role="alert">{error.message||"تعذّر الحفظ؛ المسودة محفوظة."}</p>}{options.error&&<p role="alert">{options.error}<button type="button" onClick={options.retry}>إعادة تحميل الخيارات</button></p>}
 {conflict&&<section className={layout.diagnosis}><h3>تغيّرت البيانات؛ مسودتك محفوظة</h3><button type="button" className={styles.secondary} disabled={busy} onClick={()=>void refresh()}>جلب أحدث نسخة</button>{latest&&<><p>راجع الأحدث وحدد الحقول التي تريد تطبيقها من مسودتك؛ البقية تتبع النسخة الحالية. لا حفظ تلقائي.</p>{keys.filter(key=>key!=="carry_forward"||(latest.obsolete&&(choices[kind==="void-dose"?"session_resolution":"status"]?draft:latest.values)[kind==="void-dose"?"session_resolution":"status"]==="rescheduled")).map(key=><label key={key}><input type="checkbox" checked={!!choices[key]} onChange={e=>setChoices(c=>({...c,[key]:e.target.checked}))}/>{labels[key]??key}<small>الأحدث: {String(latest.values[key]??"غير مسجل")} · مسودتي: {String(draft[key]??"غير مسجل")}</small></label>)}{kind==="dose"&&<><h4>بنود النسخة الحالية</h4><ul>{latest.items.map((x,i)=><li key={i}>{x.medication_name_snapshot} · {x.dose_value} {x.dose_unit} · {x.quantity} {x.quantity_unit}</li>)}</ul><label><input type="checkbox" checked={!!choices.items} onChange={e=>setChoices(c=>({...c,items:e.target.checked}))}/>استخدام بنود مسودتي بعد مقارنتها بالبنود الحالية أدناه</label></>}{latest.closed?<p>السجل مغلق أو مبطل؛ يمكن مراجعة المسودة ولا يمكن حفظها فوقه.</p>:<button type="button" className={styles.secondary} onClick={review}>اعتماد الاختيارات للمراجعة قبل الحفظ</button>}</>}</section>}
 <fieldset className={layout.diagnosis} disabled={busy||conflict}><legend>{titles[kind]}</legend><div className={`${styles.fields} ${oncology.fields}`}>
 {kind==="appointment"&&<>{field("planned_on")}<ClinicalContext value={context} change={v=>{setContext(v);setDraft(d=>({...d,clinic_id:v.clinic?.id??null,doctor_id:v.doctor?.id??null}));}} facility={facility} date={String(draft.planned_on??"")} prefix="" label="الطبيب الذي حدد الموعد" error={fieldError}/>{field("note")}<p className={styles.full}>موعد مستقل دون إنشاء خطة أو زيارة أو إعطاء. تُسجل الجرعة الفعلية لاحقًا من قسم أدوية الزيارة وفق شروطها.</p></>}
 {kind==="plan"&&<>{field("protocol_name")}{!!plan?.revisions[0]?.protocol_code&&<p className={styles.hint}>الكود التاريخي المحفوظ: {String(plan.revisions[0].protocol_code)}</p>}{field("modality",modalities)}{field("intent",intents)}{field("starts_on")}<details className={`${layout.optionalGroup} ${styles.full}`}><summary>تفاصيل إضافية للخطة (اختيارية)</summary><div className={styles.fields}>{field("ends_on")}{field("planned_cycles")}{field("planned_sessions")}{field("interval_days")}</div></details><ClinicalContext value={context} change={v=>{setContext(v);setDraft(d=>({...d,clinic_id:v.clinic?.id??null,doctor_id:v.doctor?.id??null}));}} facility={facility} date={String(draft.starts_on)} prefix="" label="واضع الخطة العلاجية" error={fieldError}/><Picker name="diagnosis_id" label="التشخيص المرتبط" path={`dossiers/options/diagnoses?facility_id=${facility}`} selected={draft.diagnosis_id?{id:Number(draft.diagnosis_id),name_ar:String(plan?.revisions[0]?.diagnosis_snapshot??"التشخيص المحفوظ")}:null} onSelect={v=>update("diagnosis_id",v.id)}/>{field("note")}{plan&&<>{field("amendment_reason")}<p className={styles.full}>التعديل السريري ينشئ نسخة جديدة؛ تبقى المواعيد السابقة غير مؤهلة حتى معالجتها صراحة بعد إعادة الاعتماد.</p></>}{duplicate&&<><label><input type="checkbox" checked={!!draft.confirm_duplicate} onChange={e=>update("confirm_duplicate",e.target.checked)}/>إنشاء خطة مطابقة مستقلة عن قصد</label>{field("duplicate_reason")}</>}</>}
 {kind==="status"&&<>{field("status",Object.fromEntries(Object.entries(planStates).filter(([key])=>key==="active"?p.caps.treatment_activate:p.caps.treatment_status&&(plan?.status==="draft"?["cancelled"]:["paused","completed","cancelled"]).includes(key))))}{field("reason")}{draft.status==="active"&&field("override_reason")}<p className={styles.full}>التفعيل وإعادة الاعتماد يفحصان الدليل التشخيصي الحالي. الاستثناء يحتاج صلاحية مستقلة ومبررًا صريحًا؛ تغيير الحالة لا يمحو التاريخ.</p></>}
 {kind==="session"&&<>{field("status",Object.fromEntries(Object.entries(sessionStates).filter(([key])=>["rescheduled","missed","cancelled","referred"].includes(key))))}{draft.status==="rescheduled"&&field("planned_on")}{field("reason")}{obsolete&&draft.status==="rescheduled"&&<label><input type="checkbox" checked={!!draft.carry_forward} onChange={e=>update("carry_forward",e.target.checked)}/>نقل الموعد صراحة إلى النسخة الحالية مع طبيبها وعيادتها</label>}</>}
 {actual&&<>{field(kind==="dose"?"administered_on":"dispensed_on")}{field("reporting_period_id",periods)}{!options.loading&&!options.data?.periods.length&&<p role="alert">لا توجد فترة مفتوحة تغطي هذه الواقعة؛ لا ينشئ النموذج فترة تلقائيًا.</p>}{kind==="dose"?<>{field("supervising_staff_id",doctors)}{field("administered_by",staff)}{field("session_label")}{field("note")}</>:<>{field("prescribing_staff_id",doctors)}{field("dispensing_purpose",{take_home:"دواء مصروف ليؤخذ خارج المشفى",supportive:"دواء داعم مصروف مع العلاج"})}{medication(draft,0,update,"")}</>}{(kind==="dose"&&dose||kind==="dispense"&&dispensing)&&field("reason")}</>}
 {isVoid&&<><p>إذا حدث العلاج وكانت التفاصيل خاطئة فاستخدم التصحيح. الإبطال يعني أن الإعطاء غير صالح ويُحفظ تاريخيًا؛ لا يُبطل الصرف المرتبط تلقائيًا.</p>{field("reason")}{kind==="void-dose"&&<>{field("session_resolution",{rescheduled:"إعادة الجدولة",missed:"لم يحضر",cancelled:"إلغاء الموعد",referred:"إحالة"})}{draft.session_resolution==="rescheduled"&&field("planned_on")}{obsolete&&draft.session_resolution==="rescheduled"&&<label><input type="checkbox" checked={!!draft.carry_forward} onChange={e=>update("carry_forward",e.target.checked)}/>نقل الموعد صراحة إلى النسخة الحالية</label>}</>}</>}
 </div>
 {kind==="dose"&&<section><h3>الأدوية المعطاة فعلًا</h3>{items.map((item,i)=><section className={layout.diagnosis} key={item.key??item.id??i}><h4>الدواء {i+1}</h4><div className={`${styles.fields} ${oncology.fields}`}>{medication(item,i,(key,value)=>setItems(xs=>xs.map((x,n)=>n===i?{...x,[key]:value}:x)),`items.${i}.`)}</div>{kind==="dose"&&item.id?<label><input type="checkbox" checked={!!item.remove} onChange={e=>setItems(xs=>xs.map((x,n)=>n===i?{...x,remove:e.target.checked}:x))}/>إبطال البند مع حفظ تاريخه{item.remove&&<input name={`items.${i}.void_reason`} aria-label="سبب إبطال البند" value={String(item.void_reason??"")} onChange={e=>setItems(xs=>xs.map((x,n)=>n===i?{...x,void_reason:e.target.value}:x))}/>}</label>:<button type="button" className={`${styles.secondary} ${styles.dangerText}`} onClick={()=>setItems(xs=>xs.filter((_,n)=>n!==i))}>إزالة البند من المسودة</button>}</section>)}{fieldError("items")}<button type="button" className={styles.secondary} onClick={()=>setItems(xs=>[...xs,{key:crypto.randomUUID()}])}>إضافة دواء معطى</button></section>}
 {kind==="schedule"&&<section><p>أدخل التواريخ المؤكدة صراحة؛ لن تُنشأ زيارات. راجع كل موعد قبل تأكيد الجدولة.</p>{sessions.map((s,i)=><section key={i} className={layout.diagnosis}><div className={`${styles.fields} ${oncology.fields}`}>{[["planned_on","تاريخ الجلسة","date"],["session_number","رقم الجلسة في الخطة","number"],["cycle_number","رقم الدورة (اختياري)","number"]].map(([k,label,type])=><label key={k}>{label}<input name={`sessions.${i}.${k}`} type={type} value={String(s[k])} onChange={e=>setSessions(xs=>xs.map((x,n)=>n===i?{...x,[k]:e.target.value}:x))}/>{fieldError(`sessions.${i}.${k}`)}</label>)}</div><button type="button" className={styles.secondary} onClick={()=>setSessions(xs=>xs.filter((_,n)=>n!==i))}>إزالة الموعد من المسودة</button></section>)}<button type="button" className={styles.secondary} disabled={sessions.length>=24} onClick={()=>setSessions(xs=>[...xs,{planned_on:"",session_number:"",cycle_number:"",note:""}])}>إضافة موعد آخر</button>{fieldError("sessions")}</section>}
 </fieldset><div className={styles.actions}><button type="submit" className={styles.primary} disabled={busy||conflict}>{busy?"جارٍ الحفظ…":kind==="schedule"?"تأكيد المواعيد وحفظها":isVoid?"تأكيد الإبطال":kind==="status"||kind==="session"?"تأكيد الإجراء":"حفظ"}</button><button type="button" className={styles.secondary} disabled={busy} onClick={onClose}>إلغاء</button></div></form></Modal>;
}
