import { historyLabels, treatmentLabels, sourceLabels } from "./api";
import type { Snapshot } from "./wizard";
import { prescriptionKindLabels } from "./clinical";
import { DirectoryTable } from "../directory/DirectoryPrimitives";
import { LongText } from "../directory/Controls";
import styles from "../clinics/clinics.module.css";
import layout from "./wizard.module.css";

export default function ReviewSummary({snapshot:s}:{snapshot:Snapshot}){
  const v=s.visit,c=s.clinical;
  return <section className={layout.diagnosis}><h4>مراجعة البيانات المحفوظة</h4><p className={styles.hint}>يعرض هذا الملخص آخر بيانات محفوظة. التغييرات التي لم تُحفظ في الأقسام السابقة لا تدخل في الإكمال.</p><dl className={styles.facts}><div><dt>بطاقة المريض</dt><dd>{s.patient.first_name} {s.patient.family_name} · <bdi>{s.code}</bdi></dd></div><div><dt>تاريخ الزيارة وحالتها</dt><dd>{String(v?.visit_date??"غير محفوظة")} · {v?.status==="complete"?"مكتملة":"مسودة — غير مكتملة"}</dd></div><div><dt>القصة المرضية الحالية</dt><dd><LongText text={String(s.medical.clinical_history??"")}/></dd></div><div><dt>البيانات الورمية</dt><dd>{s.medical.is_oncology?"مريض ورمي":"غير ورمي"} · {s.progress.find(p=>p.section==="medical")?.state==="saved"?"القرار محفوظ":"لم يُحفظ القرار بعد"}</dd></div><div><dt>التشخيصات</dt><dd>{v?.diagnoses.map(d=>`${d.diagnosis_name} · ${d.clinic_name??""} · ${d.doctor_name}`).join("؛ ")||"لم يُسجل تشخيص بعد"}</dd></div></dl>
    <dl className={styles.facts}><div><dt>بداية الملف الطبي في المشفى</dt><dd>{s.opening_date}</dd></div><div><dt>الوضع العائلي</dt><dd>{({unknown:"غير معروف",single:"أعزب",married:"متزوج",divorced:"مطلق",widowed:"أرمل"} as Record<string,string>)[String(s.patient.marital_status??"unknown")]??"غير مسجل"}</dd></div><div><dt>المهنة</dt><dd>{String(s.patient.occupation||"غير مسجلة")}</dd></div><div><dt>التدخين</dt><dd>{({unknown:"غير معروف",yes:"نعم",no:"لا",former:"سابقًا"} as Record<string,string>)[String(s.patient.smoking_status??"unknown")]}</dd></div><div><dt>الكحول</dt><dd>{({unknown:"غير معروف",yes:"نعم",no:"لا",former:"سابقًا"} as Record<string,string>)[String(s.patient.alcohol_status??"unknown")]}</dd></div>{s.patient.displacement_status==="idp"&&<div><dt>عنوان الإقامة الدائم</dt><dd><LongText text={String(s.patient.permanent_address??"")}/></dd></div>}<div><dt>الوزن</dt><dd>{s.medical.weight_kg?`${s.medical.weight_kg} كغ`:"غير مسجل"}</dd></div><div><dt>الطول</dt><dd>{s.medical.height_cm?`${s.medical.height_cm} سم`:"غير مسجل"}</dd></div><div><dt>معلومات الإعاقة</dt><dd><LongText text={String(s.medical.disability_text??"")}/></dd></div>{!!s.medical.is_oncology&&<><div><dt>السوابق الورمية</dt><dd>{s.medical.history.map(k=>historyLabels[k]??k).join("؛ ")||"غير مسجلة"}</dd></div><div><dt>العلاجات السابقة</dt><dd>{s.medical.treatment.map(k=>treatmentLabels[k]??k).join("؛ ")||"غير مسجلة"}</dd></div><div><dt>الفحوص السابقة</dt><dd><LongText text={String(s.medical.previous_examinations??"")}/></dd></div><div><dt>مصدر الدواء العام</dt><dd>{sourceLabels[String(s.medical.medication_source)]??"غير مسجل"}{s.medical.medication_source==="other_organization"&&` · ${String(s.medical.other_organization??"")}`}</dd></div></>}{!!v?.is_referred&&<div><dt>الإحالة الواردة</dt><dd>{String(v.referring_hospital??"")} · {String(v.referral_date??"")}<LongText text={String(v.referral_reason??"")}/></dd></div>}</dl>
    {(["procedures","services"] as const).map(kind=><div key={kind}><h4>{kind==="services"?"الخدمات":"الإجراءات"}</h4><DirectoryTable label={`مراجعة ${kind==="services"?"الخدمات":"الإجراءات"}`} headers={["البيان","العيادة","الطبيب","الملاحظة"]}>{c?.[kind].map(r=><tr key={r.id}><td>{r.name_ar}</td><td>{r.clinic_name??"غير مسجلة"}</td><td>{r.doctor_name??"غير مسجل"}</td><td><LongText text={r.note}/></td></tr>)}{!c?.[kind].length&&<tr><td colSpan={4}>قسم اختياري دون بنود محفوظة.</td></tr>}</DirectoryTable></div>)}
    {(c?.prescriptions ?? (c?.prescription ? [c.prescription] : [])).map(rx => <div key={rx.id}><h4>{prescriptionKindLabels[rx.kind ?? "unlinked"]}</h4><p>{rx.prescribed_on} · {rx.clinic_name} · {rx.doctor_name}{rx.funding_name ? ` · تمويل الوصفة: ${rx.funding_name}` : ""}</p>{rx.unavailable_reason && <p>سبب عدم التواجد في المشفى: {rx.unavailable_reason}</p>}<LongText text={rx.note}/><DirectoryTable label="مراجعة أدوية الوصفة" headers={["الدواء المحفوظ","الملاحظة"]}>{rx.items.map(i=><tr key={i.id}><td><bdi>{i.code}</bdi> · {i.name_ar}</td><td><LongText text={i.note}/></td></tr>)}</DirectoryTable></div>)}
    {!c?.prescriptions?.length && !c?.prescription && <><h4>الوصفات</h4><p>دون وصفة محفوظة.</p></>}
    <h4>نتيجة الزيارة</h4>{c?.outcome?<><p>{c.outcome.name_ar} · {c.outcome.outcome_on} · {c.outcome.clinic_name} · {c.outcome.doctor_name}</p><LongText text={c.outcome.note}/>{c.outcome.code==="DOS-REFER"&&<p>الإحالة الصادرة: {c.outcome.referral_target} · {c.outcome.outgoing_referral_date} · {c.outcome.outgoing_referral_reason}</p>}</>:<p>لم تُحفظ نتيجة بعد؛ النتيجة مطلوبة للإكمال.</p>}<p>المرفقات: {c?.attachment_count??"تحتاج صلاحية العرض"}</p>
  </section>;
}
