import { historyLabels, treatmentLabels, sourceLabels } from "./api";
import type { Snapshot } from "./wizard";
import { DirectoryTable } from "../directory/DirectoryPrimitives";
import { LongText } from "../directory/Controls";
import styles from "../clinics/clinics.module.css";
import layout from "./wizard.module.css";

export default function ReviewSummary({snapshot:s}:{snapshot:Snapshot}){
  const v=s.visit,c=s.clinical;
  return <section className={layout.diagnosis}><h4>مراجعة البيانات المحفوظة</h4><p className={styles.hint}>يعرض هذا الملخص آخر بيانات محفوظة. التغييرات التي لم تُحفظ في الأقسام السابقة لا تدخل في الإكمال.</p><dl className={styles.facts}><div><dt>بطاقة المريض</dt><dd>{s.patient.first_name} {s.patient.family_name} · <bdi>{s.code}</bdi></dd></div><div><dt>تاريخ الزيارة وحالتها</dt><dd>{String(v?.visit_date??"غير محفوظة")} · {v?.status==="complete"?"مكتملة":"مسودة — غير مكتملة"}</dd></div><div><dt>القصة المرضية الحالية</dt><dd><LongText text={String(s.medical.clinical_history??"")}/></dd></div><div><dt>البيانات الورمية</dt><dd>{s.medical.is_oncology?"مريض ورمي":"غير ورمي"} · {s.progress.find(p=>p.section==="medical")?.state==="saved"?"القرار محفوظ":"لم يُحفظ القرار بعد"}</dd></div><div><dt>التشخيصات</dt><dd>{v?.diagnoses.map(d=>`${d.diagnosis_name} · ${d.clinic_name??""} · ${d.doctor_name}`).join("؛ ")||"لم يُسجل تشخيص بعد"}</dd></div></dl>
    <dl className={styles.facts}><div><dt>بداية الملف الطبي في المشفى</dt><dd>{s.opening_date}</dd></div><div><dt>معلومات الإعاقة</dt><dd><LongText text={String(s.medical.disability_text??"")}/></dd></div>{!!s.medical.is_oncology&&<><div><dt>السوابق الورمية</dt><dd>{s.medical.history.map(k=>historyLabels[k]??k).join("؛ ")||"غير مسجلة"}</dd></div><div><dt>العلاجات السابقة</dt><dd>{s.medical.treatment.map(k=>treatmentLabels[k]??k).join("؛ ")||"غير مسجلة"}</dd></div><div><dt>الفحوص السابقة</dt><dd><LongText text={String(s.medical.previous_examinations??"")}/></dd></div><div><dt>مصدر الدواء العام</dt><dd>{sourceLabels[String(s.medical.medication_source)]??"غير مسجل"}{s.medical.medication_source==="other_organization"&&` · ${String(s.medical.other_organization??"")}`}</dd></div></>}{!!v?.is_referred&&<div><dt>الإحالة الواردة</dt><dd>{String(v.referring_hospital??"")} · {String(v.referral_date??"")}<LongText text={String(v.referral_reason??"")}/></dd></div>}</dl>
    {(["procedures","services"] as const).map(kind=><div key={kind}><h4>{kind==="services"?"الخدمات":"الإجراءات"}</h4><DirectoryTable label={`مراجعة ${kind==="services"?"الخدمات":"الإجراءات"}`} headers={["البيان","العيادة","الطبيب","الملاحظة"]}>{c?.[kind].map(r=><tr key={r.id}><td>{r.name_ar}</td><td>{r.clinic_name??"غير مسجلة"}</td><td>{r.doctor_name??"غير مسجل"}</td><td><LongText text={r.note}/></td></tr>)}{!c?.[kind].length&&<tr><td colSpan={4}>قسم اختياري دون بنود محفوظة.</td></tr>}</DirectoryTable></div>)}
    <h4>الوصفة الطبية</h4>{c?.prescription?<><p>{c.prescription.prescribed_on} · {c.prescription.clinic_name} · {c.prescription.doctor_name}</p><LongText text={c.prescription.note}/><DirectoryTable label="مراجعة أدوية الوصفة" headers={["الدواء المحفوظ","الملاحظة"]}>{c.prescription.items.map(i=><tr key={i.id}><td><bdi>{i.code}</bdi> · {i.name_ar}</td><td><LongText text={i.note}/></td></tr>)}</DirectoryTable></>:<p>دون وصفة محفوظة؛ لا يعني ذلك صرف دواء أو إعطاءه.</p>}
    <h4>نتيجة الزيارة</h4>{c?.outcome?<><p>{c.outcome.name_ar} · {c.outcome.outcome_on} · {c.outcome.clinic_name} · {c.outcome.doctor_name}</p><LongText text={c.outcome.note}/>{c.outcome.code==="DOS-REFER"&&<p>الإحالة الصادرة: {c.outcome.referral_target} · {c.outcome.outgoing_referral_date} · {c.outcome.outgoing_referral_reason}</p>}</>:<p>لم تُحفظ نتيجة بعد؛ النتيجة مطلوبة للإكمال.</p>}<p>المرفقات: {c?.attachment_count??"تحتاج صلاحية العرض"}</p>
  </section>;
}
