"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useIdentity } from "../auth/AuthenticatedLayout";
import { directoryFacility } from "../directory/facilityContext";
import { useClinicRequest } from "../clinics/api";
import styles from "../clinics/clinics.module.css";
import ui from "./settings.module.css";
import TaskGuide from "./TaskGuide";

type Guide = { facility: { id: number; name_ar: string }; permissions: string[]; global_permissions: string[]; system_admin: boolean };
export default function GuideScreen() {
  const { access } = useIdentity(), query = useSearchParams();
  const { entry } = directoryFacility(access.filter(e => e.permissions.length), null, query.get("facility_id"));
  if (!entry || query.getAll("facility_id").length > 1 || (query.has("facility_id") && !/^[1-9]\d*$/.test(query.get("facility_id")!))) return <section className={styles.status}><h2>دليل الاستخدام</h2><p role="alert">لا يتوفر سياق منشأة مسموح لهذا الرابط. يمكنك تسجيل الخروج من قائمة الحساب.</p></section>;
  return <div className={styles.screen}><div className={styles.context}><span>المنشأة</span><strong>{entry.facility.name_ar}</strong></div><GuideContent key={entry.facility.id} facility={entry.facility.id} /></div>;
}

function GuideContent({ facility }: { facility: number }) {
  const request = useClinicRequest<Guide>(`guide?facility_id=${facility}`);
  if (request.error) return <section className={styles.status}><p role="alert">{request.error}</p><button className={styles.secondary} onClick={request.retry}>إعادة المحاولة</button><p>لتسجيل الخروج افتح قائمة الحساب أعلى الصفحة.</p></section>;
  if (!request.data) return <p className={styles.status} role="status">جارٍ تحميل الدليل المسموح…</p>;
  const data = request.data, can = (code: string) => data.permissions.includes(code);
  const link = (permission: string, path: string, label: string) => can(permission) ? <Link className={styles.secondary} href={`${path}?facility_id=${facility}`}>{label}</Link> : null;
  return <div className={ui.page}><header className={styles.heading}><div><h2>دليل الاستخدام</h2><p>المهام المتاحة في {data.facility.name_ar}. تظهر الأقسام وفق صلاحياتك الفعلية، وقد يجمع حسابك أكثر من مهمة.</p></div></header>
    <TaskGuide facility={facility} permissions={data.permissions} globalPermissions={data.global_permissions??[]} />
    {data.permissions.some(p => ["users.view", "identity_corrections.review", "reception_accounts.manage", "patient_duplicates.review", "settings.view"].includes(p)) && <section className={`${styles.panel} ${ui.card}`}><h3>إداري المشفى</h3><ol><li>أنشئ المستخدم بدور فعال لا يتجاوز صلاحياتك القابلة للإسناد في المنشأة. الأدوار النظامية وأدوار التسجيل الأساسي الداخلية مستثناة. اختيار دور محلي لا يمنح تفويضًا عالميًا.</li><li>إذا ظهر تنبيه انتظار التفويض العالمي، فالحساب محفوظ لكن البحث وإنشاء هوية المريض يحتاجان مسؤول النظام. لا يحتاج حساب الإحصاء إلى تفويضات التسجيل الأساسي.</li><li>راجع التصحيحات والتكرارات مع سبب مكتوب. اعتماد تغيير هوية مشتركة أو الربط الآمن يحتاج أيضًا تفويضًا عالميًا صريحًا. التعارض يمنع تطبيق المقترح على نسخة تغيّرت.</li><li>تجميد الحسابات يقتصر على حسابات التسجيل الأساسي المؤهلة؛ يُحفظ تاريخ أعمالها وتُبطل رموزها. الحساب النظامي والمستخدم 1 والحسابات خارج النطاق محمية.</li><li>إعدادات المنشأة تحتاج صلاحية عرض مستقلة عن التعديل. اسم العرض يؤثر في الشاشات والتقارير. مدة الخمول من دقيقة إلى 60 دقيقة، وافتراضيها دقيقتان. عند تعدد المنشآت تطبق أقصر مدة متاحة للمستخدم، حتى إن كانت منشأة أخرى هي المفتوحة.</li></ol><div className={styles.actions}>{link("users.view", "/users", "إدارة المستخدمين")}{link("identity_corrections.review", "/reception-admin", "مراجعة التصحيحات")}{!can("identity_corrections.review") && link("reception_accounts.manage", "/reception-admin", "حسابات التسجيل الأساسي")}{!can("identity_corrections.review") && !can("reception_accounts.manage") && link("patient_duplicates.review", "/reception-admin", "مراجعة التكرارات")}{link("settings.view", "/settings", "إعدادات المنشأة")}{link("reports.view", "/reports", "التقارير المصرح بها")}{link("audit.view", "/audit", "سجل الحركة")}</div></section>}
    {can("statistics.view") && <section className={`${styles.panel} ${ui.card}`}><h3>فريق الإحصاء</h3><ol><li>اختر فترة من الأشهر المكتملة، حتى 12 شهرًا. لا تتضمن هذه البوابة أسماء المرضى أو أكوادهم أو روابط ملفاتهم.</li><li>عدد المرضى الفريدين يختلف عن عدد الوقائع؛ قد يتكرر المريض عبر فئات أو أشهر. لا تجمع أعداد المرضى بين الأشهر باعتبارها أشخاصًا مختلفين.</li><li>تُجمع الفئات الصغيرة مع فئة إضافية عند الحاجة دون كشف أسمائها، ويُحجب المؤشر إن لم يتحقق حد الخصوصية. المحجوب لا يعني صفرًا.</li><li>التصدير يحتاج صلاحيته ونجاح تحميل الفترة المعروضة. لا تتوفر نسبة الإشغال لعدم وجود أساس موثوق لحسابها في هذا المسار.</li></ol><div className={styles.actions}>{link("statistics.view", "/statistics", "فتح الإحصاءات المجهلة")}</div></section>}
    {data.system_admin && <section className={`${styles.panel} ${ui.card}`}><h3>مدير النظام الشامل</h3><p>يأتي الوصول من الدور النظامي وإسناده الصريح، لا من رقم المستخدم أو اسمه. يعمل في المنشآت الفعالة بالصلاحيات المحفوظة فقط؛ إلغاء اختيار صلاحية تشغيلية يسري في API والواجهة، ولا تضيف التعريفات الجديدة نفسها تلقائيًا.</p><p>يمكنك تعديل الصلاحيات من تفاصيل الدور مع سبب ومعاينة للفرق. الحد الأدنى لإدارة الوصول محمي لمنع إغلاق النظام على المسؤول. إدارة التفويض لا تشترط امتلاك كل صلاحية طبية تشغيلية، ولا تسمح بإسناد الدور المحمي لحساب آخر من الواجهة العادية.</p><p>من تفاصيل المستخدم أسند دوره المحلي، ثم فعّل التفويضات العالمية المختارة بخطوة منفصلة ومدققة. لا تمنح مجموعة التسجيل التاريخ الطبي أو التصدير أو الحذف.</p><p>سياسة جلساتك عامة ومستقلة عن إعدادات المنشأة؛ افتراضيها دقيقتان ضمن 1–60 دقيقة، وليست إعفاءً من انتهاء الجلسة. راجع التدقيق بعد القرارات الحساسة؛ تغييرات SQL الخارجية لا تُسجل تلقائيًا.</p><div className={styles.actions}>{link("roles.view", "/users", "تفاصيل الأدوار والتفويض")}{link("settings.view", "/settings", "إعدادات المنشأة والسياسة العامة")}{link("audit.view", "/audit", "مراجعة سجل الحركة")}</div></section>}
    {can("dashboards.view") && <section className={`${styles.panel} ${ui.card}`}><h3>لوحة التحكم العامة</h3><p>تُعرض مؤشرات المنشأة المسموحة. عند غياب المنشأة عن الرابط يختار الخادم الافتراضية المسموحة. الرابط الذي يحدد منشأة مرفوضة لا ينتقل بصمت إلى أخرى.</p><div className={styles.actions}>{link("dashboards.view", "/dashboard/general", "لوحة التحكم")}</div></section>}
    <section className={`${styles.panel} ${ui.card}`}><h3>الجلسة والمساعدة</h3><p>مدة الخمول قابلة للضبط، وافتراضيها دقيقتان. يظهر تحذير قرب انتهائها مع زر «متابعة الجلسة». احفظ مسودتك مبكرًا؛ التغييرات غير المحفوظة لا تستعاد تلقائيًا. الطلبات الخلفية لا تمدد الجلسة، ولا تعيد زيادة المدة جلسة منتهية.</p><p>عند تعارض النسخة، اجلب أحدث البيانات وراجع مسودتك قبل إعادة الحفظ. عند رفض الصلاحية، تواصل مع المسؤول واذكر الصفحة والمنشأة ورسالة الخطأ دون بيانات مرضى أو كلمة مرور. عند فشل الاتصال، أعد المحاولة دون تكرار عملية حفظ لم تعرف نتيجتها.</p><p>لتسجيل الخروج افتح قائمة حسابك أعلى الصفحة ثم اختر «تسجيل الخروج». عند تعذّر التحقق الأولي من الجلسة يتوفر أيضًا الخروج من المتصفح.</p></section>
  </div>;
}
