import Link from "next/link";
import { LuArrowDown, LuArrowLeft, LuCheck, LuClipboardCheck, LuDroplet, LuFilePenLine, LuFolderHeart, LuSearch, LuStethoscope } from "react-icons/lu";
import type { IconType } from "react-icons";
import styles from "../clinics/clinics.module.css";
import ui from "./guide.module.css";

type Task = { title: string; description: string; path: string; icon: IconType; steps: string[]; result: string; allowed: boolean };
export default function TaskGuide({ facility, permissions, globalPermissions }: { facility: number; permissions: string[]; globalPermissions: string[] }) {
  const can = (...codes: string[]) => codes.every(code => permissions.includes(code));
  const global = (...codes: string[]) => codes.every(code => globalPermissions.includes(code));
  const medical = can("dossiers.medical.view", "dossiers.visits.view");
  const registration = can("patient_cards.register") && (global("patients.basic.create") || global("patients.basic.search"));
  const tasks: Task[] = [
    { title: "البحث والتسجيل", description: "افتح البطاقة الموجودة أو سجّل الهوية الجديدة وفق التفويض المتاح لك.", path: "/patient-cards/new", icon: LuSearch, allowed: can("patients.basic.view") && registration, steps: [global("patients.basic.search") ? "ابحث بالاسم أو أحد المعرّفات المتاحة." : "البحث المشترك غير متاح لحسابك؛ راجع المسؤول عند الاشتباه بتكرار الهوية.", "راجع النتائج المتاحة؛ تشابه الاسم لا يعني أن الشخص نفسه.", global("patients.basic.create") ? "اختر الشخص الموجود، أو سجّل بيانات الجديد وتاريخ الزيارة الفعلي." : "اختر الهوية الموجودة وأدخل تاريخ الزيارة الفعلي؛ إنشاء هوية جديدة غير متاح لحسابك.", "احفظ؛ يُصدر النظام الكود مرة واحدة."], result: "هوية واحدة وبطاقة للمشفى وزيارة أولى مسودة؛ فتح النموذج وحده لا ينشئ شيئًا." },
    { title: "البحث وفتح البطاقة", description: "راجع الهوية والملخص الأساسي دون عرض التاريخ الطبي.", path: "/patient-cards/new", icon: LuSearch, allowed: can("patients.basic.view") && global("patients.basic.search") && !registration, steps: ["اكتب الاسم أو أحد المعرّفات المتاحة.", "راجع نتائج البحث المحدود.", "اختر فتح البطاقة الموجودة.", "راجع البيانات الأساسية والعمليات المسموحة فقط."], result: "قراءة الملخص لا تنشئ هوية أو زيارة، ولا تمنح صلاحية تسجيل." },
    { title: "استكمال مسودة محفوظة", description: "يستلم الفريق الطبي البطاقة والزيارة اللتين حفظهما موظف التسجيل.", path: "/patient-cards", icon: LuFilePenLine, allowed: medical && ["dossiers.medical.update", "dossiers.visits.draft.update", "dossiers.diagnoses.update", "dossiers.services.update", "dossiers.procedures.update", "dossiers.prescriptions.update", "dossiers.outcomes.update"].some(code => can(code)), steps: ["ابحث عن البطاقة المسودة.", "اختر استكمال بيانات البطاقة.", "أدخل الأقسام التي تملك صلاحيتها واحفظ كل قسم.", "راجع ما حُفظ؛ لا تنشئ بطاقة بديلة."], result: "تُستكمل المسودة نفسها مع الحفاظ على كود المريض ومعرّف الزيارة." },
    { title: "زيارة جديدة للمريض نفسه", description: "البطاقة ثابتة، ولكل زيارة تاريخها وبياناتها.", path: "/visits", icon: LuStethoscope, allowed: medical && can("dossiers.visits.create"), steps: ["افتح قائمة الزيارات واختر إضافة زيارة.", "حدد بطاقة المريض الموجودة.", "أدخل تاريخ الزيارة الفعلي والأقسام المتاحة.", "احفظ الزيارة الجديدة كمسودة."], result: "تُضاف زيارة إلى البطاقة نفسها، ولا تتكرر هوية المريض." },
    { title: "مراجعة الزيارة وإكمالها", description: "المسودة قابلة للاستكمال؛ الإكمال قرار مستقل بعد المراجعة.", path: "/patient-cards", icon: LuClipboardCheck, allowed: medical && can("dossiers.visits.complete"), steps: ["افتح الزيارة المسودة المحفوظة.", "راجع الأقسام والنتيجة والحقول المطلوبة.", "حدد العيادة والطبيب المؤهلين.", "أكد الإكمال بعد المراجعة."], result: "تُسجّل الزيارة مكتملة. هذا لا يفعّل البطاقة تلقائيًا ولا ينشئ صرفًا أو إعطاءً." },
    { title: "طلب تصحيح بيانات المريض", description: "اقترح التصحيح مع سبب؛ لا تُغيّر الهوية المشتركة دون مراجعة.", path: "/patient-cards/new", icon: LuFilePenLine, allowed: can("patients.basic.view", "patients.corrections.request") && global("patients.basic.search"), steps: ["ابحث عن المريض وافتح ملخصه الأساسي.", "راجع نافذة التصحيح المباشر إن كانت متاحة لك.", "أدخل الحقول المقترحة وسبب الطلب.", "تابع حالة الطلب من الملخص نفسه."], result: "يبقى السجل دون تغيير حتى موافقة المسؤول المخوّل؛ التعارض يتطلب مراجعة جديدة." },
    { title: "مراجعة طلبات التصحيح", description: "قارن القيم الحالية والمقترحة وأثرها قبل القرار.", path: "/reception-admin", icon: LuClipboardCheck, allowed: can("identity_corrections.review"), steps: ["افتح الطلب المطلوب.", "راجع القيم الحالية والمقترحة وصاحب الطلب.", "تحقق من أثر التصحيح في الهوية المشتركة.", "سجّل القرار وسببه إذا كان لديك التفويض اللازم."], result: global("patients.identity.review") ? "الموافقة تطبق التصحيح ذريًا على النسخة المراجعة وتسجّل القرار." : "يمكنك المراجعة؛ تطبيق تغيير الهوية المشتركة يحتاج تفويضًا عالميًا مستقلًا." },
    { title: "تسجيل واقعة بنك الدم", description: "ميّز التبرع عن صرف المكوّن وعن نقل الدم الفعلي.", path: "/blood-bank", icon: LuDroplet, allowed: can("blood_bank.view") && ["blood_bank.donations.create", "blood_bank.issue.create", "blood_bank.transfusion.create"].some(code => can(code)), steps: ["اختر العملية المتاحة لك وحدد الشخص.", "أدخل تاريخ الواقعة والكمية بالكيلوغرام.", "راجع زمرة الواقعة واربط الصرف بالنقل عند الحاجة.", "احفظ مرة واحدة ثم راجع الكود في السجل."], result: "تُحفظ الواقعة بنوعها؛ صرف المكوّن لا يعني إجراء نقل دم تلقائيًا." },
    { title: "خطة العلاج وموعد الجرعة", description: "الخطة والمواعيد تختلف عن الإعطاء الفعلي.", path: "/patient-cards", icon: LuStethoscope, allowed: medical && can("dossiers.treatment.view") && ["dossiers.treatment.create", "dossiers.treatment.schedule.create"].some(code => can(code)), steps: ["افتح مساحة العمل الطبية للبطاقة.", "اختر إضافة خطة أو موعد بدون خطة بحسب صلاحيتك.", "حدد الطبيب والتاريخ وراجع البيانات.", "احفظ؛ يُسجّل الإعطاء لاحقًا بعملية مستقلة."], result: "موعد محفوظ لا ينشئ زيارة أو إعطاء جرعة تلقائيًا." },
  ];
  return <>
    <section className={ui.hero} aria-labelledby="guide-purpose"><div><span className={ui.eyebrow}>دليل المهام · خطوة بخطوة</span><h2 id="guide-purpose">ماذا تريد أن تفعل؟</h2><p>ابدأ بمهمة واضحة، ثم اتبع الخطوات إلى نتيجة محفوظة. تظهر هنا المهام التي تسمح بها صلاحياتك، وتبقى شروط السجل مطبّقة عند الحفظ.</p></div><LuFolderHeart className={ui.heroIcon} aria-hidden="true" /></section>
    <section className={ui.diagram} aria-labelledby="card-visit-diagram"><header><span className={ui.eyebrow}>افهم العلاقة أولًا</span><h3 id="card-visit-diagram">بطاقة واحدة… وزيارات متعددة</h3><p>البيانات الشخصية تخص الشخص؛ لكل زيارة تاريخ فعلي وبيانات مستقلة داخل المشفى.</p></header><div className={ui.relationship}><div className={ui.patientCard}><LuFolderHeart aria-hidden="true" /><strong>بطاقة المريض</strong><span>هوية وكود ثابتان</span><small>تاريخ فتح البطاقة ≠ تاريخ الزيارة</small></div><div className={ui.connector} aria-hidden="true"><LuArrowLeft/><LuArrowDown/></div><div className={ui.visits}>{[["١", "الزيارة الأولى", "مسودة", "يبدأ التسجيل ثم يستكمله الفريق الطبي"], ["٢", "زيارة لاحقة", "مكتملة", "نتيجة محفوظة بعد المراجعة والإكمال"], ["٣", "زيارة جديدة", "تاريخ فعلي", "تُضاف إلى البطاقة نفسها"]].map(([n,title,state,note])=><div className={ui.visit} key={n}><b>{n}</b><div><strong>{title}</strong><span>{note}</span></div><em>{state}</em></div>)}</div></div></section>
    <section className={ui.example} aria-labelledby="guide-example"><header><span className={ui.eyebrow}>مثال توضيحي — بيانات افتراضية</span><h3 id="guide-example">من البحث عن «أحمد» إلى استكمال زيارته</h3><p>هذا شرح للعملية، وليس سجل مريض أو أمرًا لإنشاء بيانات.</p></header><ol className={ui.steps}>{[
      [LuSearch, "ابحث وراجع", "بحث أحمد محمد", "تظهر بطاقة موجودة؟ افتحها. لا توجد مطابقة مؤكدة؟ سجّل شخصًا جديدًا."],
      [LuFolderHeart, "سجّل الأساسيات", "تاريخ الزيارة الفعلي: يحدده الموظف", "أدخل البيانات المتاحة والتاريخ الفعلي؛ لا تعتمد تاريخ اليوم افتراضيًا."],
      [LuCheck, "احفظ المسودة", "بطاقة واحدة · زيارة أولى مسودة", "بعد نجاح الحفظ يظهر الكود النظامي. تكرار النقر لا ينشئ تسجيلًا ثانيًا."],
      [LuStethoscope, "سلّم للاستكمال", "فتح المسودة المحفوظة نفسها", "يفتح المخوّل الاستكمال لإضافة البيانات الطبية، ثم يراجعها قبل إكمال الزيارة."],
    ].map(([Icon,title,caption,note],i)=>{const Illustration=Icon as IconType;return <li key={String(title)}><div className={ui.stepNumber}>{i+1}</div><div className={ui.illustration}><Illustration aria-hidden="true"/><span>{String(caption)}</span></div><h4>{String(title)}</h4><p>{String(note)}</p><LuArrowLeft className={ui.stepArrow} aria-hidden="true"/></li>;})}</ol><p className={ui.result}><LuCheck aria-hidden="true"/> النتيجة: لا مريض مكرر ولا زيارة أولى ثانية عند انتقال العمل بين الموظفين.</p></section>
    <div className={ui.tasks}>{tasks.filter(task=>task.allowed).map(task=><article className={ui.task} key={task.title}><task.icon className={ui.taskIcon} aria-hidden="true"/><h3>{task.title}</h3><p>{task.description}</p><ol>{task.steps.map(step=><li key={step}>{step}</li>)}</ol><p className={ui.result}><LuCheck aria-hidden="true"/>{task.result}</p><Link className={styles.primary} href={`${task.path}?facility_id=${facility}`}>ابدأ: {task.title}<LuArrowLeft aria-hidden="true"/></Link></article>)}</div>
    {!tasks.some(task=>task.allowed)&&<p className={styles.status}>لا توجد مهام تسجيل أو عمل طبي متاحة لهذا الحساب. الأقسام الإدارية أو الإحصائية المسموحة موضّحة أدناه.</p>}
    <section className={ui.help}><h3>إذا توقفت الخطوة، ماذا تفعل؟</h3><dl>{[["نتيجة بحث فارغة", "راجع الاسم والمعرّف، وجرّب جزءًا أدق من الاسم قبل إنشاء هوية جديدة."],["نقص صلاحية", "اطلب من المسؤول المهمة اللازمة؛ ظهور البطاقة لا يعني السماح بكل إجراءاتها."],["تعارض تعديل", "اجلب أحدث نسخة وراجع الفروق مع مسودتك ثم اختر ما تريد تطبيقه؛ لا تحفظ فوق تعديل زميلك."],["انقطاع اتصال أو فشل حفظ", "تبقى المسودة في الصفحة ما دامت مفتوحة. أعد المحاولة من الزر نفسه، وتحقق من نتيجة الحفظ قبل إنشاء تسجيل آخر."]].map(([title,note])=><div key={title}><dt>{title}</dt><dd>{note}</dd></div>)}</dl></section>
  </>;
}
