import assert from 'node:assert/strict';
import { before, after, test } from 'node:test';
import { spawnSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright';
const base = 'http://127.0.0.1:3194'; let f, browser;
const gallery = new URL('../.superdesign/tmp/dossier-review-regression/', import.meta.url);
function fixture(mode) { const r = spawnSync('php', ['tests/Support/dossier-review-live.php', mode], { cwd: fileURLToPath(new URL('../../backend/', import.meta.url)), env: process.env, encoding: 'utf8' }); assert.equal(r.status, 0, r.stdout + r.stderr); assert.doesNotMatch(r.stdout+r.stderr,/In .+ line|Exception/); process.stdout.write(r.stdout); }
before(async () => { fixture('prepare'); f = JSON.parse(readFileSync(new URL('../../backend/storage/framework/testing/dossier-review-live.json', import.meta.url))); browser = await chromium.launch(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{}); await mkdir(gallery, { recursive: true }); });
after(async () => { await browser?.close(); fixture('cleanup'); });
async function api(method, path, data = {}, token = f.token) { const fields = { facility_id: f.facility, ...data }; const r = await fetch(`${base}/hospital-api/dossiers${path}${method === 'GET' ? '?' + new URLSearchParams(fields) : ''}`, { method, headers: { Accept: 'application/json', 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, ...(method === 'GET' ? {} : { body: JSON.stringify(fields) }) }); assert.equal(r.headers.get('x-test-laravel'), 'dossiers'); assert.match(r.headers.get('cache-control'), /no-store/); return { status: r.status, body: await r.json() }; }
async function open(width, path, token = f.token, delayOptions = false) { const context = await browser.newContext({ viewport: { width, height: 1000 }, reducedMotion: 'reduce' }); await context.addInitScript(({ token, delayOptions }) => { sessionStorage.setItem('hospital.bearer', token); if (delayOptions) { const original = window.fetch; window.fetch = async (...args) => { const result = await original(...args); if (String(args[0]).includes('/dossiers/options?')) await new Promise(r => setTimeout(r, 1200)); return result; }; } }, { token, delayOptions }); const page = await context.newPage(); page.on('pageerror', error => console.error('Browser error:', error.message)); page.on('response', response => { if (response.status() >= 500) console.error('Server error:', response.status(), new URL(response.url()).pathname); }); page.setDefaultTimeout(15000); page.on('dialog', d => d.accept()); await page.goto(`${base}${path}${path.includes('?') ? '&' : '?'}facility_id=${f.facility}`); return { page, context }; }
async function capture(page, name) { if (process.env.DOSSIER_REVIEW_BEFORE === '1') return; await page.evaluate(async () => { await document.fonts.ready; window.scrollTo(0, 0); }); assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false); await page.screenshot({ path: fileURLToPath(new URL(`${name}.jpg`, gallery)), type: 'jpeg', quality: 78, fullPage: true }); }

test('review procedure count column reflects scoped server aggregate at all widths', async () => {
  for (const width of [390, 768, 1440]) { const { page, context } = await open(width, '/patient-cards'); try { await page.getByRole('region', { name: 'جدول بطاقات المرضى', exact: true }).waitFor(); await page.locator('summary').filter({hasText:'الأعمدة'}).click(); await page.getByRole('checkbox',{name:'عدد الإجراءات',exact:true}).check(); await page.locator('summary').filter({hasText:'الأعمدة'}).click(); assert.equal(await page.getByRole('columnheader', { name: 'عدد الإجراءات', exact: true }).count(), 1); const result = await api('GET', '', { search: `DOS-${f.tag}-001` }); assert.equal(result.body.data[0].procedure_count, 4); const row = page.getByRole('row').filter({ has: page.getByText(`${f.tag}-P1`, { exact: true }) }); const headers = await page.getByRole('region', { name: 'جدول بطاقات المرضى', exact: true }).getByRole('columnheader').allTextContents(); assert.equal(await row.locator('td').nth(headers.indexOf('عدد الإجراءات')).innerText(), '4'); await page.getByRole('columnheader', { name: 'عدد الإجراءات', exact: true }).scrollIntoViewIfNeeded(); await capture(page, `procedure-count-${width}`); } finally { await context.close(); } }
});

test('review creation and initial visit actions match actual identity and operation capabilities', async () => {
  for (const width of [390, 768, 1440]) {
    const { page, context } = await open(width, '/patient-cards', f.no_identity_token, true);
    try { await page.getByRole('heading', { name: 'بطاقات المرضى', exact: true, level: 2 }).waitFor(); assert.equal(await page.getByText('تحتاج الإضافة صلاحية إنشاء بطاقة مريض وتسجيل زيارة.', { exact: true }).count(), 0); await page.waitForTimeout(1500); assert.equal(await page.getByRole('button', { name: 'تسجيل بطاقة مريض', exact: true }).isDisabled(), true); await page.getByText('إنشاء بطاقة المريض يحتاج أيضًا صلاحية البحث عن مريض أو إنشاء مريض جديد.', { exact: true }).waitFor(); await page.goto(`${base}/patient-cards/new?facility_id=${f.facility}`); await page.getByText('إنشاء بطاقة المريض يحتاج أيضًا صلاحية البحث عن مريض أو إنشاء مريض جديد.', { exact: true }).waitFor(); assert.equal(await page.locator('[name="code"]').count(), 0); await capture(page, `identity-access-${width}`); } finally { await context.close(); }
    for (const token of [f.search_token, f.new_patient_token]) { const { page, context } = await open(width, '/patient-cards', token); try {
      await page.getByRole('link', { name: 'تسجيل بطاقة مريض', exact: true }).click();
      const existing = token === f.search_token;
      const mode = page.getByRole('radio', { name: existing ? 'ربط بطاقة موجودة من مشفى آخر' : 'تسجيل بطاقة مريض جديدة', exact: true });
      await mode.waitFor(); assert.equal(await mode.isChecked(), true);
      assert.equal(await page.locator('[name="code"]').count(), existing ? 0 : 1);
      assert.equal(await page.getByRole('button', { name: 'اختيار: المريض الموجود', exact: true }).count(), existing ? 1 : 0);
    } finally { await context.close(); } }
    for (const [id, token, expected] of [[f.empty_dossier, f.visit_create_token, 'تسجيل أول زيارة مسجلة ضمن البطاقة'], [f.empty_dossier, f.visit_update_token, null], [f.context_dossier, f.visit_create_token, null], [f.context_dossier, f.visit_update_token, 'استكمال أول زيارة مسجلة ضمن البطاقة المسودة']]) { const { page, context } = await open(width, `/patient-cards/${id}`, token); try { await page.getByRole('heading', { name: 'بيانات المريض الحالية', exact: true }).waitFor(); await page.waitForTimeout(300); if (expected) { await page.getByRole('link', { name: expected, exact: true }).waitFor(); await page.getByRole('link', { name: 'استكمال بيانات البطاقة', exact: true }).click(); await page.getByRole('heading', { name: 'الزيارة والتشخيصات', exact: true }).waitFor(); } else assert.equal(await page.getByRole('link', { name: /استكمال بيانات البطاقة|مراجعة أول زيارة مسجلة ضمن البطاقة|تسجيل أول زيارة مسجلة ضمن البطاقة|استكمال أول زيارة مسجلة ضمن البطاقة/ }).count(), 0); } finally { await context.close(); } }
  }
});

test('review existing-patient selection blocks submission and a real creation race preserves the draft', async () => {
  for (const width of [390, 768, 1440]) { const { page, context } = await open(width, '/patient-cards/new', f.search_token); try {
    try { await page.locator('[name="opening_date"]').fill('1999-02-03'); } catch (error) { console.error('Registration page failed to open:', width, await page.locator('main').innerText()); throw error; }
    await page.getByRole('button',{name:'اختيار: المريض الموجود',exact:true}).click(); const picker = page.getByRole('group', { name: 'المريض الموجود', exact: true }); await picker.getByRole('searchbox').fill(f.search_patient_code); await picker.getByRole('button', { name: f.search_patient_name + ' (' + f.search_patient_code + ')', exact: true }).click();
    await page.getByRole('link', { name: 'فتح البطاقة / إضافة زيارة', exact: true }).waitFor(); assert.equal(await page.getByRole('button', { name: 'حفظ ومتابعة', exact: true }).isDisabled(), true);
    let writes = 0; page.on('request', r => { if (r.method() === 'POST' && new URL(r.url()).pathname === '/hospital-api/dossiers') writes++; }); await page.getByRole('button', { name: 'حفظ ومتابعة', exact: true }).evaluate(el => el.click()); assert.equal(writes, 0);
    await page.getByRole('button', { name: 'اختيار مريض آخر', exact: true }).click(); await page.locator('[name="visit_date"]').fill('2001-03-02'); await page.getByRole('button',{name:'اختيار: المريض الموجود',exact:true}).click(); await picker.getByRole('searchbox').fill(`RACE-${f.tag}-${width}`); await picker.getByRole('button').filter({ hasText: `RACE-${f.tag}-${width}` }).click();
    const created = await api('POST', '', { request_id: crypto.randomUUID(), person_mode: 'existing', patient_id: f.race_patients[width], visit_date: '2001-03-02', opening_date: '2000-01-01' }); assert.equal(created.status, 201);
    const response = page.waitForResponse(r => r.request().method() === 'POST' && new URL(r.url()).pathname === '/hospital-api/dossiers'); await page.getByRole('button', { name: 'حفظ ومتابعة', exact: true }).click(); assert.equal((await response).status(), 409);
    await page.getByRole('link', { name: 'فتح البطاقة / إضافة زيارة', exact: true }).waitFor(); assert.equal(await page.locator('[name="code"]').count(), 0); assert.equal(await page.locator('[name="opening_date"]').inputValue(), '1999-02-03'); assert.equal(await page.getByRole('button', { name: 'جلب أحدث نسخة', exact: true }).count(), 0); await capture(page, `existing-conflict-${width}`);
    await page.getByRole('button', { name: 'اختيار مريض آخر', exact: true }).click(); assert.equal(await page.locator('[name="code"]').count(), 0);
    const result = await api('GET', '', { search: `RACE-${f.tag}-${width}` }); assert.equal(result.body.totals.dossiers, 1); assert.equal(result.body.data[0].id, created.body.data.id);
  } finally { await context.close(); } }
});

test('review historical context rechecks the new date through Next and keeps failed browser/server drafts', async () => {
  for (const width of [390, 768, 1440]) { const { page, context } = await open(width, `/patient-cards/${f.context_dossier}/edit?section=2`); try { await page.locator('[name="visit_date"]').waitFor(); const before = (await api('GET', `/${f.context_dossier}/progress`)).body.data; await page.locator('[name="visit_date"]').fill('2002-01-01'); const response = page.waitForResponse(r => r.request().method() === 'PUT' && r.url().includes(`/visits/${f.context_visit}`)); await page.getByRole('button', { name: 'حفظ ومتابعة', exact: true }).click(); const r = await response; assert.equal(r.status(), 422); assert.ok((await r.json()).errors['diagnoses.0.diagnosing_staff_id']); assert.equal(await page.locator('[name="visit_date"]').inputValue(), '2002-01-01'); assert.deepEqual((await api('GET', `/${f.context_dossier}/progress`)).body.data, before); await capture(page, `date-context-error-${width}`); } finally { await context.close(); } }
});
