import assert from 'node:assert/strict';
import {before,after,test} from 'node:test';
import {spawnSync} from 'node:child_process';
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {randomUUID} from 'node:crypto';
import {chromium} from 'playwright';
const base='http://127.0.0.1:3194',artifacts=new URL('../.superdesign/tmp/oncology/',import.meta.url);
let f,browser,last;
function fixture(mode){const r=spawnSync('php',['tests/Support/oncology-live.php',mode],{cwd:fileURLToPath(new URL('../../backend/',import.meta.url)),env:{...process.env,APP_ENV:'testing'},encoding:'utf8'});assert.equal(r.status,0,r.stdout+r.stderr);assert.doesNotMatch(r.stdout+r.stderr,/Exception|In .+ line/);process.stdout.write(r.stdout);}
before(async()=>{fixture('prepare');f=JSON.parse(readFileSync(new URL('../../backend/storage/framework/testing/oncology-live.json',import.meta.url)));browser=await chromium.launch(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{});mkdirSync(artifacts,{recursive:true});});
after(async()=>{await browser?.close();fixture('cleanup');});
async function api(method,path,data={},token=f.token){const query=method==='GET'?`${path.includes('?')?'&':'?'}facility_id=${data.facility_id??f.facility}`:'';const r=await fetch(`${base}/hospital-api/dossiers${path}${query}`,{method,headers:{Accept:'application/json','Content-Type':'application/json',Authorization:token?`Bearer ${token}`:''},...method==='GET'?{}:{body:JSON.stringify({facility_id:f.facility,request_id:randomUUID(),...data})}});assert.equal(r.headers.get('x-test-laravel'),'dossiers');assert.match(r.headers.get('cache-control'),/no-store/);return{status:r.status,body:await r.json()};}
const item=()=>({medication_id:f.medication,dose_value:'2.5',dose_unit:'mg',route:'IV',quantity:'1.5',quantity_unit:'vial',medication_source:'ministry_of_health'});
const planBody=(text,extra={})=>({protocol_text:text,modality:'chemotherapy',intent:'curative',protocol_clinic_id:f.clinics[0],protocol_doctor_id:f.workflow_doctors[0],treating_clinic_id:f.clinics[0],treating_doctor_id:f.workflow_doctors[0],...extra});
async function create(){let r=await api('POST','',{person_mode:'new',code:'ONC-'+randomUUID().slice(0,18),opening_date:'2001-01-01',visit_date:'2001-03-02',first_name:'مريض',family_name:'علاج اصطناعي',birth_date_accuracy:'unknown',gender:'unknown',displacement_status:'unknown'});assert.equal(r.status,201,JSON.stringify(r.body));let d=r.body.data;r=await api('PUT',`/${d.id}/visits/${d.visit.id}`,{lock_version:d.visit.lock_version,visit_date:'2001-03-02',is_referred:false,diagnoses:[{diagnosis_id:f.diagnosis,diagnosed_on:null,clinic_id:f.clinics[0],diagnosing_staff_id:f.workflow_doctors[0]}]});assert.equal(r.status,200,JSON.stringify(r.body));d=r.body.data;
 const path=`/${d.id}/visits/${d.visit.id}`;r=await api('POST',`${path}/pathology`,{source:'external',external_organization:'مختبر اصطناعي',status:'completed',result_on:'2001-02-01',conclusion:'دليل اصطناعي مكتمل'});assert.equal(r.status,201);const evidence=r.body.data.id;r=await api('PUT',`${path}/diagnostic-assessment`,{lock_version:0,disposition:'pathology_confirmed',evidence_pathology_id:evidence,assessed_on:'2001-03-02'});assert.equal(r.status,200);return{...d,evidence};}
async function save(page,method,suffix,label='حفظ'){const response=page.waitForResponse(r=>r.request().method()===method&&r.url().split('?')[0].endsWith(suffix));await page.getByRole('dialog').getByRole('button',{name:label,exact:true}).click();const r=await response;assert.ok(r.ok(),await r.text());await page.getByRole('dialog').waitFor({state:'hidden'});return(await r.json()).data;}
async function shot(page,name){await page.evaluate(async()=>{await document.fonts.ready;});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),name);assert.ok(await page.getByRole('dialog').locator('button[aria-pressed]').evaluateAll(buttons=>buttons.every(button=>{const label=button.querySelector('span');if(!label)return true;const box=button.getBoundingClientRect(),text=label.getBoundingClientRect();return !box.width||text.height<=box.height+2;})),name+' readable picker labels');await page.screenshot({path:fileURLToPath(new URL(name+'.png',artifacts)),fullPage:true});await page.screenshot({path:fileURLToPath(new URL(name+'-viewport.png',artifacts))});}
test('real plan, explicit scheduling, administration, dispensing and reports at all responsive widths',async()=>{
 for(const width of [390,768,1440]){const d=await create();last=d;const ctx=await browser.newContext({viewport:{width,height:1000},reducedMotion:'reduce'});await ctx.addInitScript(t=>sessionStorage.setItem('hospital.bearer',t),f.token);const page=await ctx.newPage();page.setDefaultTimeout(20000);
 try{await page.goto(`${base}/patient-cards/new?card=${d.id}&visit=${d.visit.id}&facility_id=${f.facility}&section=7`);await page.getByRole('button',{name:'إضافة خطة علاجية',exact:true}).click();let dialog=page.getByRole('dialog');
  const invalid=page.waitForResponse(r=>r.status()===422&&r.request().method()==='POST');await dialog.getByRole('button',{name:'حفظ',exact:true}).click();await invalid;await page.waitForFunction(()=>document.activeElement?.getAttribute('name')==='modality');await shot(page,`plan-errors-${width}`);
  await dialog.locator('[name="protocol_text"]').fill('=بروتوكول اصطناعي 00012');assert.equal(await dialog.locator('[name="protocol_name"]').count(),0);assert.equal(await dialog.locator('[name="starts_on"]').count(),0);assert.equal(await dialog.getByRole("button",{name:"إضافة دواء مخطط",exact:true}).count(),0);await dialog.locator('[name="modality"]').selectOption('chemotherapy');await dialog.locator('[name="intent"]').selectOption('curative');
  for(const label of ['الطبيب المسؤول عن وضع البروتوكول','الطبيب المعالج']){await dialog.getByRole('button',{name:`اختيار: العيادة · ${label}`,exact:true}).click();await dialog.getByRole('group',{name:`العيادة · ${label}`,exact:true}).getByRole('button').first().click();await dialog.getByRole('button',{name:`اختيار: ${label}`,exact:true}).click();await dialog.getByRole('group',{name:label,exact:true}).getByRole('button').first().click();}await shot(page,`plan-editor-${width}`);let p=await save(page,'POST','/treatment-plans');d.plan=p;
  let r=await api('POST',`/${d.id}/treatment-plans/${p.id}/status`,{lock_version:p.lock_version,status:'active',reason:'مراجعة الدليل الحالي'});assert.equal(r.status,200,JSON.stringify(r.body));p=r.body.data;
  await page.reload();await page.getByRole('button',{name:'فتح الخطة',exact:true}).click();await page.getByRole('button',{name:'إضافة موعد للخطة',exact:true}).click();dialog=page.getByRole('dialog');await dialog.locator('[name="sessions.0.planned_on"]').fill('2090-01-01');assert.equal(await dialog.locator('[name="sessions.0.session_number"]').count(),0);await dialog.getByRole('button',{name:'إضافة موعد',exact:true}).click();await dialog.locator('[name="sessions.1.planned_on"]').fill('2090-02-01');await shot(page,`schedule-${width}`);await save(page,'POST',`/treatment-plans/${p.id}/sessions`,'تأكيد المواعيد وحفظها');
  await page.getByRole('button',{name:'إضافة جرعة علاجية',exact:true}).first().click();dialog=page.getByRole('dialog');assert.equal(await dialog.locator('[name="given_on"]').inputValue(),'2090-01-01');await dialog.locator('[name="dose_name"]').fill('الجرعة الأولى');await dialog.locator('[name="complaint"]').fill('غثيان بعد الموعد');await dialog.locator('[name="recommendations"]').fill('إكمال الجلسة مع مراقبة');assert.deepEqual(await dialog.locator('[name="medication_source"] option').allTextContents(),['اختر…','وزارة الصحة','مؤسسة الرواد','جهة أخرى','نفقة شخصية','لا يوجد']);await dialog.locator('[name="medication_source"]').selectOption('ministry_of_health');await dialog.locator('[name="nurse_id"]').selectOption({index:1});await save(page,'POST','/session-doses');
  await page.goto(`${base}/patient-cards/new?card=${d.id}&visit=${d.visit.id}&facility_id=${f.facility}&section=8`);
  const region=page.getByRole('region',{name:'العلاج الفعلي للزيارة',exact:true});
  let scheduled=(await api('GET',`/${d.id}/treatment-sessions`)).body.data;let current=(await api('GET',`/${d.id}/treatment-plans/${p.id}`)).body.data;
  const doseInput=s=>({session_id:s.id,session_lock_version:s.lock_version,plan_lock_version:current.lock_version,visit_lock_version:d.visit.lock_version,administered_on:'2001-03-02',supervising_staff_id:f.workflow_doctors[0],administered_by:f.workflow_doctors[0],reporting_period_id:f.period,items:[item()]});
  const mismatch=await api('POST',`/${d.id}/visits/${d.visit.id}/doses`,doseInput(scheduled[0]));assert.equal(mismatch.status,422);assert.equal(mismatch.body.error.code,'ONCOLOGY_SCHEDULE_DATE_MISMATCH');assert.equal(await region.getByRole('button',{name:'تسجيل إعطاء جرعة',exact:true}).count(),0);
  await region.getByRole('button',{name:'تغيير الموعد أو حالته',exact:true}).first().click();dialog=page.getByRole('dialog');await dialog.locator('[name="status"]').selectOption('rescheduled');await dialog.locator('[name="planned_on"]').fill('2001-03-02');await dialog.locator('[name="reason"]').fill('تصحيح صريح لتاريخ الحضور التاريخي');await shot(page,`reschedule-${width}`);await save(page,'PUT',`/treatment-sessions/${scheduled[0].id}`,'تأكيد الإجراء');
  await region.getByRole('button',{name:'تسجيل إعطاء جرعة',exact:true}).first().click();dialog=page.getByRole('dialog');assert.equal(await dialog.locator('[name="reporting_period_id"]').count(),0);await dialog.locator('[name="supervising_staff_id"]').selectOption(String(f.workflow_doctors[0]));await dialog.locator('[name="administered_by"]').selectOption(String(f.workflow_doctors[0]));await dialog.getByRole('button',{name:'إضافة دواء معطى',exact:true}).click();await dialog.getByRole('button',{name:'اختيار: الدواء من الدليل 1',exact:true}).click();await dialog.getByRole('group',{name:'الدواء من الدليل 1',exact:true}).getByRole('searchbox').fill('RX-'+f.tag);await dialog.getByRole('group',{name:'الدواء من الدليل 1',exact:true}).getByRole('button').first().click();for(const[k,v]of Object.entries({dose_value:'2.5',dose_unit:'mg',route:'IV',quantity:'1.5',quantity_unit:'vial'}))await dialog.locator(`[name="items.0.${k}"]`).fill(v);assert.deepEqual(await dialog.locator('[name="items.0.medication_source"] option').allTextContents(),['اختر…','وزارة الصحة','مؤسسة الرواد','جهة أخرى','نفقة شخصية','لا يوجد']);await dialog.locator('[name="items.0.medication_source"]').selectOption('ministry_of_health');await shot(page,`administration-${width}`);const saved=await save(page,'POST','/doses');d.dose=saved.id;
  await region.getByRole('button',{name:'دواء مرتبط بهذه الجرعة',exact:true}).click();dialog=page.getByRole('dialog');assert.equal(await dialog.locator('[name="reporting_period_id"]').count(),0);await dialog.locator('[name="prescribing_staff_id"]').selectOption(String(f.workflow_doctors[0]));assert.equal(await dialog.locator('[name="dispensing_purpose"]').count(),0);await dialog.getByRole('button',{name:'اختيار: الدواء من الدليل 1',exact:true}).click();await dialog.getByRole('group',{name:'الدواء من الدليل 1',exact:true}).getByRole('searchbox').fill('RX-'+f.tag);await dialog.getByRole('group',{name:'الدواء من الدليل 1',exact:true}).getByRole('button').first().click();await dialog.locator('[name="quantity"]').fill('3.5');await dialog.locator('[name="quantity_unit"]').fill('tablet');await dialog.locator('[name="medication_source"]').selectOption('al_rowad');await shot(page,`dispensing-${width}`);await save(page,'POST','/dispensing');
  await page.goto(`${base}/patient-cards/new?card=${d.id}&visit=${d.visit.id}&facility_id=${f.facility}&section=4`);
  for(const [tab,button,purpose] of [['صرف خارج المشفى','تسجيل صرف خارج المشفى','take_home'],['صرف غير مرتبط بالجرعة','تسجيل صرف غير مرتبط بالجرعة','unlinked']]){await page.getByRole('tab',{name:tab,exact:true}).click();const meds=page.getByRole('region',{name:'صرف أدوية الزيارة',exact:true});await meds.getByText('الأدوية المرتبطة بالجرعة تُفتح فقط عند تسجيل الجرعة.',{exact:true}).waitFor();await meds.getByRole('button',{name:button,exact:true}).click();dialog=page.getByRole('dialog');assert.equal(await dialog.locator('[name="reporting_period_id"]').count(),0);await dialog.getByRole('button',{name:'اختيار: العيادة · الصرف',exact:true}).click();await dialog.getByRole('group',{name:'العيادة · الصرف',exact:true}).getByRole('button').first().click();await dialog.getByRole('button',{name:'اختيار: الطبيب المسؤول عن الصرف',exact:true}).click();await dialog.getByRole('group',{name:'الطبيب المسؤول عن الصرف',exact:true}).getByRole('button').first().click();await dialog.getByRole('button',{name:'اختيار: الدواء من الدليل 1',exact:true}).click();await dialog.getByRole('group',{name:'الدواء من الدليل 1',exact:true}).getByRole('searchbox').fill('RX-'+f.tag);await dialog.getByRole('group',{name:'الدواء من الدليل 1',exact:true}).getByRole('button').first().click();await dialog.locator('[name="quantity"]').fill('1');await dialog.locator('[name="quantity_unit"]').fill('tablet');await dialog.locator('[name="medication_source"]').selectOption(purpose==='take_home'?'personal_expense':'other_organization');await save(page,'POST','/dispensing');assert.equal(purpose==='take_home'||purpose==='unlinked',true);}
  await shot(page,`detail-${width}`);
  const stored=await api('GET',`/${d.id}/visits/${d.visit.id}/doses`);assert.equal(stored.body.data.doses.length,1);assert.equal(stored.body.data.dispensed.length,3);assert.equal(stored.body.data.doses[0].items[0].dose_value,'2.5000');assert.equal(stored.body.data.doses[0].reporting_period_id,null);assert.equal(stored.body.data.doses[0].items[0].medication_source,'ministry_of_health');assert.deepEqual(stored.body.data.dispensed.map(row=>row.dispensing_purpose),['supportive','take_home','unlinked']);assert.deepEqual(stored.body.data.dispensed.map(row=>row.medication_source),['al_rowad','personal_expense','other_organization']);assert.ok(stored.body.data.dispensed.every(row=>row.reporting_period_id==null));assert.equal(stored.body.data.dispensed[1].dose_session_id,null);assert.equal(stored.body.data.dispensed[2].dose_session_id,null);
  await page.goto(`${base}/patient-cards/new?card=${d.id}&visit=${d.visit.id}&facility_id=${f.facility}&section=8`);
  current=(await api('GET',`/${d.id}/treatment-plans/${p.id}`)).body.data;
  const revision=current.revisions[0];r=await api('PUT',`/${d.id}/treatment-plans/${p.id}`,{...revision,lock_version:current.lock_version,protocol_text:'=بروتوكول اصطناعي معدل 00012'});assert.equal(r.status,200,JSON.stringify(r.body));current=r.body.data;
  r=await api('POST',`/${d.id}/treatment-plans/${p.id}/status`,{lock_version:current.lock_version,status:'active',reason:'اعتماد النسخة المعدلة'});assert.equal(r.status,200);current=r.body.data;
  scheduled=(await api('GET',`/${d.id}/treatment-sessions`)).body.data;const obsolete=scheduled.find(s=>s.session_number===2);r=await api('POST',`/${d.id}/visits/${d.visit.id}/doses`,doseInput(obsolete));assert.equal(r.status,422);assert.equal(r.body.error.code,'ONCOLOGY_OBSOLETE_SESSION_REVISION');
  await page.reload();await region.getByText('نسخة علاجية سابقة — تحتاج معالجة قبل الإعطاء',{exact:true}).waitFor();await region.getByRole('button',{name:'تغيير الموعد أو حالته',exact:true}).click();dialog=page.getByRole('dialog');await dialog.locator('[name="status"]').selectOption('rescheduled');await dialog.locator('[name="reason"]').fill('نقل صريح إلى النسخة المعتمدة');await dialog.getByRole('checkbox',{name:'نقل الموعد صراحة إلى النسخة الحالية مع طبيبها وعيادتها'}).check();for(const terminal of ['cancelled','missed','referred']){await dialog.locator('[name="status"]').selectOption(terminal);assert.equal(await dialog.getByRole('checkbox',{name:/نقل الموعد صراحة/}).count(),0);assert.equal(await dialog.locator('[name="planned_on"]').count(),0);await dialog.locator('[name="status"]').selectOption('rescheduled');assert.equal(await dialog.getByRole('checkbox',{name:/نقل الموعد صراحة/}).isChecked(),false);await dialog.getByRole('checkbox',{name:/نقل الموعد صراحة/}).check();}assert.equal(await dialog.locator('[name="planned_on"]').getAttribute('required'),'');await dialog.locator('[name="planned_on"]').fill('');const missingDate=page.waitForResponse(r=>r.status()===422&&r.request().method()==='PUT');await dialog.getByRole('button',{name:'تأكيد الإجراء',exact:true}).click();await missingDate;await page.waitForFunction(()=>document.activeElement?.getAttribute('name')==='planned_on');assert.equal(await dialog.locator('[name="reason"]').inputValue(),'نقل صريح إلى النسخة المعتمدة');await shot(page,`carry-date-errors-${width}`);await dialog.locator('[name="planned_on"]').fill('2090-02-01');await shot(page,`carry-forward-${width}`);await save(page,'PUT',`/treatment-sessions/${obsolete.id}`,'تأكيد الإجراء');
  await region.getByRole('button',{name:'إبطال الإعطاء',exact:true}).click();dialog=page.getByRole('dialog');await dialog.locator('[name="reason"]').fill('إعطاء اصطناعي مسجل خطأ');await dialog.locator('[name="session_resolution"]').selectOption('rescheduled');await dialog.locator('[name="planned_on"]').fill('2001-03-02');await dialog.getByRole('checkbox',{name:'نقل الموعد صراحة إلى النسخة الحالية',exact:true}).check();await dialog.locator('[name="session_resolution"]').selectOption('cancelled');assert.equal(await dialog.getByRole('checkbox',{name:/نقل الموعد صراحة/}).count(),0);await dialog.locator('[name="session_resolution"]').selectOption('rescheduled');assert.equal(await dialog.getByRole('checkbox',{name:/نقل الموعد صراحة/}).isChecked(),false);assert.equal(await dialog.locator('[name="planned_on"]').getAttribute('required'),'');await dialog.getByRole('checkbox',{name:/نقل الموعد صراحة/}).check();await shot(page,`void-resolution-${width}`);await save(page,'POST',`/doses/${d.dose}/void`,'تأكيد الإبطال');
  await region.getByText('صرف فعال مستقل مرتبط بإعطاء مبطل',{exact:true}).waitFor();scheduled=(await api('GET',`/${d.id}/treatment-sessions`)).body.data;const replacement=scheduled.find(s=>s.session_number===1);assert.equal(replacement.dose_id,null);assert.equal(replacement.has_voided_dose,true);r=await api('POST',`/${d.id}/visits/${d.visit.id}/doses`,doseInput(replacement));assert.equal(r.status,201,JSON.stringify(r.body));assert.notEqual(r.body.data.id,d.dose);const activeId=r.body.data.id;scheduled=(await api('GET',`/${d.id}/treatment-sessions`)).body.data;assert.equal(scheduled.length,2);assert.equal(scheduled.filter(s=>s.session_number===1).length,1);assert.equal(scheduled.find(s=>s.session_number===1).dose_id,activeId);assert.equal(scheduled.find(s=>s.session_number===1).has_voided_dose,true);
  const attempts=(await api('GET',`/${d.id}/visits/${d.visit.id}/doses`)).body.data;assert.equal(attempts.doses.length,2);assert.equal(attempts.doses.filter(x=>!x.voided_at).length,1);assert.equal(attempts.doses.find(x=>x.id===d.dose).plan_revision_id,p.current_revision_id);assert.equal(attempts.dispensed[0].voided_at,null);await page.reload();await region.getByText('صرف فعال مستقل مرتبط بإعطاء مبطل',{exact:true}).waitFor();await region.getByText('توجد وقائع إعطاء مبطلة محفوظة تاريخيًا',{exact:true}).waitFor();await shot(page,`corrected-history-${width}`);
  await page.goto(`${base}/patient-cards?facility_id=${f.facility}&treatment_status=active`);await page.getByRole('region',{name:'جدول بطاقات المرضى'}).waitFor();await shot(page,`list-${width}`);
 }finally{await ctx.close();}}
 for(const[kind,endpoint]of[['card',`/${last.id}/report`],['visit',`/${last.id}/visits/${last.visit.id}/report`],['list','/export']])for(const format of ['pdf','xlsx']){const r=await fetch(`${base}/hospital-api/dossiers${endpoint}/${format}`,{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json',Authorization:`Bearer ${f.token}`},body:JSON.stringify({facility_id:f.facility,...kind==='list'?{search:last.code,columns:['code','name','active_treatment_count','next_dose_on','last_dose_on']}:{} })});assert.equal(r.status,200,await r.clone().text());writeFileSync(new URL(`${kind}.${format}`,artifacts),Buffer.from(await r.arrayBuffer()));}
 fixture('verify');
});
test('conflicting plan amendment keeps the draft and requires explicit field review',async()=>{
 const d=await create();const input=planBody('الخطة قبل التعارض');let r=await api('POST',`/${d.id}/treatment-plans`,input);assert.equal(r.status,201);const p=r.body.data;
 const ctx=await browser.newContext();await ctx.addInitScript(t=>sessionStorage.setItem('hospital.bearer',t),f.token);const page=await ctx.newPage();try{await page.goto(`${base}/patient-cards/new?card=${d.id}&visit=${d.visit.id}&facility_id=${f.facility}&section=7`);await page.getByRole('button',{name:'تعديل الخطة',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.locator('[name="intent"]').selectOption('palliative');r=await api('PUT',`/${d.id}/treatment-plans/${p.id}`,{...input,lock_version:p.lock_version,protocol_text:'تعديل الطبيب الآخر'});assert.equal(r.status,200);const conflict=page.waitForResponse(r=>r.status()===409);await dialog.getByRole('button',{name:'حفظ',exact:true}).click();await conflict;assert.equal(await dialog.locator('[name="intent"]').inputValue(),'palliative');await dialog.getByRole('button',{name:'جلب أحدث نسخة',exact:true}).click();await dialog.getByText('الأحدث: تعديل الطبيب الآخر',{exact:false}).waitFor();await dialog.getByRole('checkbox',{name:/النية العلاجية/}).check();await dialog.getByRole('button',{name:'اعتماد الاختيارات للمراجعة قبل الحفظ',exact:true}).click();assert.equal(await dialog.locator('[name="protocol_text"]').inputValue(),'تعديل الطبيب الآخر');assert.equal(await dialog.locator('[name="intent"]').inputValue(),'palliative');await save(page,'PUT',`/treatment-plans/${p.id}`);r=await api('GET',`/${d.id}/treatment-plans/${p.id}`);assert.equal(r.body.data.revisions[0].protocol_text,'تعديل الطبيب الآخر');assert.equal(r.body.data.revisions[0].intent,'palliative');assert.equal(r.body.data.revisions.length,3);
 }finally{await ctx.close();}
});
test('session conflict review preserves the draft and current versions without implicit carry-forward',async()=>{
 const d=await create();const input=planBody('خطة مراجعة الموعد');let r=await api('POST',`/${d.id}/treatment-plans`,input);assert.equal(r.status,201);let p=r.body.data;r=await api('POST',`/${d.id}/treatment-plans/${p.id}/status`,{lock_version:p.lock_version,status:'active',reason:'مراجعة'});p=r.body.data;r=await api('POST',`/${d.id}/treatment-plans/${p.id}/sessions`,{lock_version:p.lock_version,sessions:[{session_number:1,planned_on:'2001-03-02'}]});assert.equal(r.status,201);const s=(await api('GET',`/${d.id}/treatment-sessions`)).body.data[0];
 const context=await browser.newContext();await context.addInitScript(t=>sessionStorage.setItem('hospital.bearer',t),f.token);const page=await context.newPage();try{await page.goto(`${base}/patient-cards/new?card=${d.id}&visit=${d.visit.id}&facility_id=${f.facility}&section=8`);const region=page.getByRole('region',{name:'العلاج الفعلي للزيارة',exact:true});await region.getByRole('button',{name:'تغيير الموعد أو حالته',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.locator('[name="status"]').selectOption('rescheduled');await dialog.locator('[name="reason"]').fill('مسودتي للموعد');r=await api('PUT',`/${d.id}/treatment-sessions/${s.id}`,{lock_version:s.lock_version,plan_lock_version:s.plan_lock_version,status:'rescheduled',planned_on:'2001-03-03',reason:'تصحيح الطبيب الآخر'});assert.equal(r.status,200);
 const conflict=page.waitForResponse(r=>r.status()===409);await dialog.getByRole('button',{name:'تأكيد الإجراء',exact:true}).click();await conflict;assert.equal(await dialog.locator('[name="reason"]').inputValue(),'مسودتي للموعد');await dialog.getByRole('button',{name:'جلب أحدث نسخة',exact:true}).click();await dialog.getByText('الأحدث: تصحيح الطبيب الآخر',{exact:false}).waitFor();await dialog.getByRole('checkbox',{name:/سبب الإجراء أو التصحيح/}).check();await dialog.getByRole('button',{name:'اعتماد الاختيارات للمراجعة قبل الحفظ',exact:true}).click();assert.equal(await dialog.locator('[name="planned_on"]').inputValue(),'2001-03-03');await save(page,'PUT',`/treatment-sessions/${s.id}`,'تأكيد الإجراء');r=await api('GET',`/${d.id}/treatment-sessions/${s.id}`);assert.equal(r.body.data.reason,'مسودتي للموعد');assert.equal(r.body.data.revision_id,s.revision_id);
 }finally{await context.close();}
});

test('obsolete-session conflict review keeps terminal resolution separate from carry-forward at every width',async()=>{
 for(const width of [390,768,1440]){const d=await create();let r=await api('POST',`/${d.id}/treatment-plans`,planBody('مراجعة نسخة الموعد'));assert.equal(r.status,201);let p=r.body.data;r=await api('POST',`/${d.id}/treatment-plans/${p.id}/status`,{lock_version:p.lock_version,status:'active',reason:'اعتماد'});assert.equal(r.status,200);p=r.body.data;r=await api('POST',`/${d.id}/treatment-plans/${p.id}/sessions`,{lock_version:p.lock_version,sessions:[{session_number:1,planned_on:'2001-03-02'}]});assert.equal(r.status,201);let s=(await api('GET',`/${d.id}/treatment-sessions`)).body.data[0];p=(await api('GET',`/${d.id}/treatment-plans/${p.id}`)).body.data;r=await api('PUT',`/${d.id}/treatment-plans/${p.id}`,{...p.revisions[0],lock_version:p.lock_version,treating_clinic_id:f.clinics[1],treating_doctor_id:f.workflow_doctors[1]});assert.equal(r.status,200);p=r.body.data;r=await api('POST',`/${d.id}/treatment-plans/${p.id}/status`,{lock_version:p.lock_version,status:'active',reason:'اعتماد النسخة الجديدة'});assert.equal(r.status,200);p=r.body.data;s=(await api('GET',`/${d.id}/treatment-sessions`)).body.data[0];
 const ctx=await browser.newContext({viewport:{width,height:1000},reducedMotion:'reduce'});await ctx.addInitScript(t=>sessionStorage.setItem('hospital.bearer',t),f.token);const page=await ctx.newPage();page.setDefaultTimeout(20000);try{
  await page.goto(`${base}/patient-cards/new?card=${d.id}&visit=${d.visit.id}&facility_id=${f.facility}&section=8`);const region=page.getByRole('region',{name:'العلاج الفعلي للزيارة',exact:true});await region.getByRole('button',{name:'تغيير الموعد أو حالته',exact:true}).click();const dialog=page.getByRole('dialog');assert.equal(await dialog.getByRole('checkbox',{name:/نقل الموعد صراحة/}).count(),0);await dialog.locator('[name="status"]').selectOption('rescheduled');await dialog.locator('[name="reason"]').fill('مسودتي باقية بعد التعارض');await dialog.getByRole('checkbox',{name:/نقل الموعد صراحة/}).check();
  r=await api('PUT',`/${d.id}/treatment-sessions/${s.id}`,{lock_version:s.lock_version,plan_lock_version:p.lock_version,status:'cancelled',reason:'إلغاء الطبيب الآخر'});assert.equal(r.status,200);const conflict=page.waitForResponse(r=>r.status()===409);await dialog.getByRole('button',{name:'تأكيد الإجراء',exact:true}).click();await conflict;await dialog.getByRole('button',{name:'جلب أحدث نسخة',exact:true}).click();await dialog.getByText('الأحدث: إلغاء الطبيب الآخر',{exact:false}).waitFor();await dialog.getByRole('checkbox',{name:/سبب الإجراء أو التصحيح/}).check();await dialog.getByRole('button',{name:'اعتماد الاختيارات للمراجعة قبل الحفظ',exact:true}).click();assert.equal(await dialog.locator('[name="status"]').inputValue(),'cancelled');assert.equal(await dialog.getByRole('checkbox',{name:/نقل الموعد صراحة/}).count(),0);assert.equal(await dialog.locator('[name="planned_on"]').count(),0);assert.equal(await dialog.locator('[name="reason"]').inputValue(),'مسودتي باقية بعد التعارض');await shot(page,`terminal-conflict-${width}`);const request=page.waitForRequest(r=>r.method()==='PUT'&&r.url().split('?')[0].endsWith(`/treatment-sessions/${s.id}`));await save(page,'PUT',`/treatment-sessions/${s.id}`,'تأكيد الإجراء');assert.equal((await request).postDataJSON().carry_forward,false);
  r=await api('GET',`/${d.id}/treatment-sessions/${s.id}`);for(const key of ['revision_id','clinic_id','doctor_id','planned_on'])assert.equal(r.body.data[key],s[key]);assert.equal(r.body.data.status,'cancelled');assert.equal(await region.getByRole('button',{name:'تسجيل إعطاء جرعة',exact:true}).count(),0);
  await region.getByRole('button',{name:'تغيير الموعد أو حالته',exact:true}).click();await dialog.locator('[name="status"]').selectOption('rescheduled');assert.equal(await dialog.getByRole('checkbox',{name:/نقل الموعد صراحة/}).isChecked(),false);await dialog.locator('[name="planned_on"]').fill('2001-03-02');await dialog.getByRole('checkbox',{name:/نقل الموعد صراحة/}).check();await save(page,'PUT',`/treatment-sessions/${s.id}`,'تأكيد الإجراء');r=await api('GET',`/${d.id}/treatment-sessions/${s.id}`);assert.equal(r.body.data.revision_id,p.current_revision_id);assert.equal(r.body.data.clinic_id,f.clinics[1]);assert.equal(r.body.data.doctor_id,f.workflow_doctors[1]);await region.getByRole('button',{name:'تسجيل إعطاء جرعة',exact:true}).waitFor();await region.getByRole('button',{name:'تغيير الموعد أو حالته',exact:true}).click();assert.equal(await dialog.getByRole('checkbox',{name:/نقل الموعد صراحة/}).count(),0);
 }finally{await ctx.close();}}
});

test('treatment columns and filters are absent without permission and stale requests remain forbidden',async()=>{
 const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.addInitScript(t=>sessionStorage.setItem('hospital.bearer',t),f.denied_token);const page=await context.newPage();
 try{await page.goto(`${base}/patient-cards?facility_id=${f.facility}`);await page.getByRole('region',{name:'جدول بطاقات المرضى'}).waitFor();await page.locator('summary').filter({hasText:'الأعمدة'}).click();assert.ok(await page.getByRole('checkbox',{name:'كود المريض',exact:true}).count());for(const label of ['عدد الخطط','الخطط الفعالة','خطط تحتاج مراجعة','أنماط العلاج الفعال','الجرعة المجدولة القادمة','آخر إعطاء فعلي'])assert.equal(await page.getByRole('checkbox',{name:label,exact:true}).count(),0,label);assert.equal(await page.locator('select[name="treatment_status"]').count(),0);
 assert.equal((await api('GET','?treatment_status=active',{},f.denied_token)).status,403);assert.equal((await api('POST','/export/xlsx',{columns:['code','active_treatment_count']},f.denied_token)).status,403);await shot(page,'permission-columns-1440');
 }finally{await context.close();}
});

test('competing real database connections serialize UUID replay and reject stale correction',()=>{fixture('concurrency');});
test('real evidence invalidation keeps the plan active and preserves administered history, scope and UUID rules',async()=>{
 assert.ok(last);let r=await api('GET',`/${last.id}/treatment-plans/${last.plan.id}`);const p=r.body.data;r=await api('GET',`/${last.id}/treatment-sessions`);const s=r.body.data.find(x=>['scheduled','rescheduled'].includes(x.status));assert.ok(s);
 assert.equal((await api('POST',`/${last.id}/visits/${last.visit.id}/pathology/${last.evidence}/void`,{lock_version:1,void_reason:'سحب الدليل للاختبار'})).status,200);
 r=await api('GET',`/${last.id}/treatment-plans/${p.id}`);assert.equal(r.body.data.effective_status,'active');
 const open=s;const plan=r.body.data;
 const moved=await api('PUT',`/${last.id}/treatment-sessions/${open.id}`,{lock_version:open.lock_version,plan_lock_version:plan.lock_version,status:'rescheduled',planned_on:'2001-03-02',reason:'الخطة تبقى فعالة بعد سحب الدليل',...open.revision_id!==open.current_revision_id?{carry_forward:true}:{}});
 assert.equal(moved.status,200,JSON.stringify(moved.body));
 const fresh=(await api('GET',`/${last.id}/treatment-sessions/${open.id}`)).body.data;
 const input={session_id:fresh.id,session_lock_version:fresh.lock_version,plan_lock_version:plan.lock_version,visit_lock_version:last.visit.lock_version,administered_on:'2001-03-02',supervising_staff_id:f.workflow_doctors[0],administered_by:f.workflow_doctors[0],reporting_period_id:f.period,items:[item()]};
 assert.equal((await api('POST',`/${last.id}/visits/${last.visit.id}/doses`,input)).status,201);
 r=await api('GET',`/${last.id}/visits/${last.visit.id}/doses`);assert.equal(r.body.data.doses.length,3);
 assert.equal((await api('GET',`/${last.id}/treatment-plans`,{},f.denied_token)).status,403);assert.equal((await api('GET',`/${last.id}/treatment-plans`,{},'')).status,401);assert.equal((await api('GET',`/${last.id}/treatment-plans`,{facility_id:f.other})).status,403);
 for(const path of ['/abc/treatment-plans','/1/treatment-plans/no/status','/1/arbitrary']){const r=await fetch(`${base}/hospital-api/dossiers${path}`);assert.equal(r.status,404);assert.equal(r.headers.get('x-test-laravel'),null);}
});
