import assert from 'node:assert/strict';
import {before,after,test} from 'node:test';
import {spawnSync} from 'node:child_process';
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {randomUUID} from 'node:crypto';
import {chromium} from 'playwright';
const base='http://127.0.0.1:3194',artifacts=new URL('../.superdesign/tmp/oncology/',import.meta.url);
let f,browser,last;
function fixture(mode){const r=spawnSync('php',['tests/Support/oncology-live.php',mode],{cwd:fileURLToPath(new URL('../../backend/',import.meta.url)),env:{...process.env,APP_ENV:'testing'},encoding:'utf8'});assert.equal(r.status,0,r.stdout+r.stderr);assert.doesNotMatch(r.stdout+r.stderr,/Exception|In .+ line/);process.stdout.write(r.stdout);}
before(async()=>{fixture('prepare');f=JSON.parse(readFileSync(new URL('../../backend/storage/framework/testing/oncology-live.json',import.meta.url)));browser=await chromium.launch();mkdirSync(artifacts,{recursive:true});});
after(async()=>{await browser?.close();fixture('cleanup');});
async function api(method,path,data={},token=f.token){const query=method==='GET'?`${path.includes('?')?'&':'?'}facility_id=${data.facility_id??f.facility}`:'';const r=await fetch(`${base}/hospital-api/dossiers${path}${query}`,{method,headers:{Accept:'application/json','Content-Type':'application/json',Authorization:token?`Bearer ${token}`:''},...method==='GET'?{}:{body:JSON.stringify({facility_id:f.facility,request_id:randomUUID(),...data})}});assert.equal(r.headers.get('x-test-laravel'),'dossiers');assert.match(r.headers.get('cache-control'),/no-store/);return{status:r.status,body:await r.json()};}
const item=()=>({medication_id:f.medication,dose_value:'2.5',dose_unit:'mg',route:'IV',quantity:'1.5',quantity_unit:'vial',funding_source_id:f.funding});
async function create(){let r=await api('POST','',{person_mode:'new',code:'ONC-'+randomUUID().slice(0,18),opening_date:'2001-01-01',visit_date:'2001-03-02',visit_type_id:f.visit_type,first_name:'مريض',family_name:'علاج اصطناعي',birth_date_accuracy:'unknown',gender:'unknown',displacement_status:'unknown'});assert.equal(r.status,201,JSON.stringify(r.body));let d=r.body.data;r=await api('PUT',`/${d.id}/visits/${d.visit.id}`,{lock_version:d.visit.lock_version,visit_date:'2001-03-02',visit_type_id:f.visit_type,is_referred:false,diagnoses:[{diagnosis_id:f.diagnosis,diagnosed_on:null,clinic_id:f.clinics[0],diagnosing_staff_id:f.workflow_doctors[0]}]});assert.equal(r.status,200,JSON.stringify(r.body));d=r.body.data;
 const path=`/${d.id}/visits/${d.visit.id}`;r=await api('POST',`${path}/pathology`,{source:'external',external_organization:'مختبر اصطناعي',status:'completed',result_on:'2001-02-01',conclusion:'دليل اصطناعي مكتمل'});assert.equal(r.status,201);const evidence=r.body.data.id;r=await api('PUT',`${path}/diagnostic-assessment`,{lock_version:0,disposition:'pathology_confirmed',evidence_pathology_id:evidence,assessed_on:'2001-03-02'});assert.equal(r.status,200);return{...d,evidence};}
async function save(page,method,suffix,label='حفظ'){const response=page.waitForResponse(r=>r.request().method()===method&&r.url().split('?')[0].endsWith(suffix));await page.getByRole('dialog').getByRole('button',{name:label,exact:true}).click();const r=await response;assert.ok(r.ok(),await r.text());await page.getByRole('dialog').waitFor({state:'hidden'});return(await r.json()).data;}
async function shot(page,name){await page.evaluate(async()=>{await document.fonts.ready;});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),name);assert.ok(await page.getByRole('dialog').locator('button[aria-pressed]').evaluateAll(buttons=>buttons.every(button=>{const label=button.querySelector('span');if(!label)return true;const box=button.getBoundingClientRect(),text=label.getBoundingClientRect();return !box.width||text.height<=box.height+2;})),name+' readable picker labels');await page.screenshot({path:fileURLToPath(new URL(name+'.png',artifacts)),fullPage:true});await page.screenshot({path:fileURLToPath(new URL(name+'-viewport.png',artifacts))});}
test('real plan, explicit scheduling, administration, dispensing and reports at all responsive widths',async()=>{
 for(const width of [390,768,1440]){const d=await create();last=d;const ctx=await browser.newContext({viewport:{width,height:1000},reducedMotion:'reduce'});await ctx.addInitScript(t=>sessionStorage.setItem('hospital.bearer',t),f.token);const page=await ctx.newPage();page.setDefaultTimeout(20000);
 try{await page.goto(`${base}/patient-cards/${d.id}?facility_id=${f.facility}`);await page.getByRole('button',{name:'إضافة خطة علاجية',exact:true}).click();let dialog=page.getByRole('dialog');
  const invalid=page.waitForResponse(r=>r.status()===422&&r.request().method()==='POST');await dialog.getByRole('button',{name:'حفظ',exact:true}).click();await invalid;await page.waitForFunction(()=>document.activeElement?.getAttribute('name')==='modality');await shot(page,`plan-errors-${width}`);
  await dialog.locator('[name="protocol_name"]').fill('=بروتوكول اصطناعي 00012');await dialog.locator('[name="protocol_code"]').fill('00012');await dialog.locator('[name="modality"]').selectOption('chemotherapy');await dialog.locator('[name="intent"]').selectOption('curative');await dialog.locator('[name="starts_on"]').fill('2001-03-02');
  await dialog.getByRole('group',{name:'العيادة · الخطة العلاجية',exact:true}).getByRole('button').first().click();await dialog.getByRole('group',{name:'الطبيب المسؤول · الخطة العلاجية',exact:true}).getByRole('button').first().click();await shot(page,`plan-editor-${width}`);let p=await save(page,'POST','/treatment-plans');d.plan=p;
  let r=await api('POST',`/${d.id}/treatment-plans/${p.id}/status`,{lock_version:p.lock_version,status:'active',reason:'مراجعة الدليل الحالي'});assert.equal(r.status,200,JSON.stringify(r.body));p=r.body.data;
  await page.reload();await page.getByRole('button',{name:'جدولة جلسات',exact:true}).click();dialog=page.getByRole('dialog');await dialog.locator('[name="sessions.0.planned_on"]').fill('2090-01-01');await dialog.locator('[name="sessions.0.session_number"]').fill('1');await dialog.getByRole('button',{name:'إضافة موعد آخر',exact:true}).click();await dialog.locator('[name="sessions.1.planned_on"]').fill('2090-02-01');await dialog.locator('[name="sessions.1.session_number"]').fill('2');await shot(page,`schedule-${width}`);await save(page,'POST',`/treatment-plans/${p.id}/sessions`,'تأكيد المواعيد وحفظها');
  const region=page.getByRole('region',{name:'العلاج الفعلي للزيارة',exact:true});await region.getByRole('button',{name:'تسجيل إعطاء جرعة',exact:true}).first().click();dialog=page.getByRole('dialog');await dialog.locator('[name="reporting_period_id"]').selectOption(String(f.period));await dialog.locator('[name="supervising_staff_id"]').selectOption(String(f.workflow_doctors[0]));await dialog.locator('[name="administered_by"]').selectOption(String(f.workflow_doctors[0]));await dialog.getByRole('button',{name:'إضافة دواء معطى',exact:true}).click();await dialog.getByRole('group',{name:'الدواء من الدليل 1',exact:true}).getByRole('searchbox').fill('RX-'+f.tag);await dialog.getByRole('group',{name:'الدواء من الدليل 1',exact:true}).getByRole('button').first().click();for(const[k,v]of Object.entries({dose_value:'2.5',dose_unit:'mg',route:'IV',quantity:'1.5',quantity_unit:'vial'}))await dialog.locator(`[name="items.0.${k}"]`).fill(v);await dialog.locator('[name="items.0.funding_source_id"]').selectOption(String(f.funding));await shot(page,`administration-${width}`);const saved=await save(page,'POST','/doses');d.dose=saved.id;
  await region.getByRole('button',{name:'تسجيل دواء مصروف مع الجرعة',exact:true}).click();dialog=page.getByRole('dialog');await dialog.locator('[name="reporting_period_id"]').selectOption(String(f.period));await dialog.locator('[name="prescribing_staff_id"]').selectOption(String(f.workflow_doctors[0]));await dialog.locator('[name="dispensing_purpose"]').selectOption('take_home');await dialog.getByRole('group',{name:'الدواء من الدليل 1',exact:true}).getByRole('searchbox').fill('RX-'+f.tag);await dialog.getByRole('group',{name:'الدواء من الدليل 1',exact:true}).getByRole('button').first().click();await dialog.locator('[name="quantity"]').fill('3.5');await dialog.locator('[name="quantity_unit"]').fill('tablet');await dialog.locator('[name="funding_source_id"]').selectOption(String(f.funding));await shot(page,`dispensing-${width}`);await save(page,'POST','/dispensing');await shot(page,`detail-${width}`);
  const stored=await api('GET',`/${d.id}/visits/${d.visit.id}/doses`);assert.equal(stored.body.data.doses.length,1);assert.equal(stored.body.data.dispensed.length,1);assert.equal(stored.body.data.doses[0].items[0].dose_value,'2.5000');assert.equal(stored.body.data.dispensed[0].dispensing_purpose,'take_home');
  await page.goto(`${base}/patient-cards?facility_id=${f.facility}&treatment_status=active`);await page.getByRole('region',{name:'جدول بطاقات المرضى'}).waitFor();await shot(page,`list-${width}`);
 }finally{await ctx.close();}}
 for(const[kind,endpoint]of[['card',`/${last.id}/report`],['visit',`/${last.id}/visits/${last.visit.id}/report`],['list','/export']])for(const format of ['pdf','xlsx']){const r=await fetch(`${base}/hospital-api/dossiers${endpoint}/${format}`,{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json',Authorization:`Bearer ${f.token}`},body:JSON.stringify({facility_id:f.facility,...kind==='list'?{search:last.code,columns:['code','name','active_treatment_count','next_dose_on','last_dose_on']}:{} })});assert.equal(r.status,200,await r.clone().text());writeFileSync(new URL(`${kind}.${format}`,artifacts),Buffer.from(await r.arrayBuffer()));}
 fixture('verify');
});
test('conflicting plan amendment keeps the draft and requires explicit field review',async()=>{
 const d=await create();const input={protocol_name:'الخطة قبل التعارض',modality:'chemotherapy',intent:'curative',starts_on:'2001-03-02',clinic_id:f.clinics[0],doctor_id:f.workflow_doctors[0],items:[]};let r=await api('POST',`/${d.id}/treatment-plans`,input);assert.equal(r.status,201);const p=r.body.data;
 const ctx=await browser.newContext();await ctx.addInitScript(t=>sessionStorage.setItem('hospital.bearer',t),f.token);const page=await ctx.newPage();try{await page.goto(`${base}/patient-cards/${d.id}?facility_id=${f.facility}`);await page.getByRole('button',{name:'تعديل الخطة',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.locator('[name="note"]').fill('مسودتي المحفوظة');r=await api('PUT',`/${d.id}/treatment-plans/${p.id}`,{...input,lock_version:p.lock_version,protocol_name:'تعديل الطبيب الآخر'});assert.equal(r.status,200);const conflict=page.waitForResponse(r=>r.status()===409);await dialog.getByRole('button',{name:'حفظ',exact:true}).click();await conflict;assert.equal(await dialog.locator('[name="note"]').inputValue(),'مسودتي المحفوظة');await dialog.getByRole('button',{name:'جلب أحدث نسخة',exact:true}).click();await dialog.getByText('الأحدث: تعديل الطبيب الآخر',{exact:false}).waitFor();await dialog.getByRole('checkbox',{name:/ملاحظة/}).check();await dialog.getByRole('button',{name:'اعتماد الاختيارات للمراجعة قبل الحفظ',exact:true}).click();assert.equal(await dialog.locator('[name="protocol_name"]').inputValue(),'تعديل الطبيب الآخر');assert.equal(await dialog.locator('[name="note"]').inputValue(),'مسودتي المحفوظة');await save(page,'PUT',`/treatment-plans/${p.id}`);r=await api('GET',`/${d.id}/treatment-plans/${p.id}`);assert.equal(r.body.data.revisions[0].protocol_name,'تعديل الطبيب الآخر');assert.equal(r.body.data.revisions[0].note,'مسودتي المحفوظة');assert.equal(r.body.data.revisions.length,3);
 }finally{await ctx.close();}
});
test('competing real database connections serialize UUID replay and reject stale correction',()=>{fixture('concurrency');});
test('real evidence invalidation blocks new facts and preserves administered history, scope and UUID rules',async()=>{
 assert.ok(last);let r=await api('GET',`/${last.id}/treatment-plans/${last.plan.id}`);const p=r.body.data;r=await api('GET',`/${last.id}/treatment-sessions`);const s=r.body.data.find(x=>x.status==='scheduled');assert.ok(s);
 assert.equal((await api('POST',`/${last.id}/visits/${last.visit.id}/pathology/${last.evidence}/void`,{lock_version:1,void_reason:'سحب الدليل للاختبار'})).status,200);
 r=await api('GET',`/${last.id}/treatment-plans/${p.id}`);assert.equal(r.body.data.effective_status,'needs_review');
 const input={session_id:s.id,session_lock_version:s.lock_version,plan_lock_version:p.lock_version,visit_lock_version:last.visit.lock_version,administered_on:'2001-03-02',supervising_staff_id:f.workflow_doctors[0],administered_by:f.workflow_doctors[0],reporting_period_id:f.period,items:[item()]};
 assert.equal((await api('POST',`/${last.id}/visits/${last.visit.id}/doses`,input)).status,422);r=await api('GET',`/${last.id}/visits/${last.visit.id}/doses`);assert.equal(r.body.data.doses.length,1);
 assert.equal((await api('GET',`/${last.id}/treatment-plans`,{},f.denied_token)).status,403);assert.equal((await api('GET',`/${last.id}/treatment-plans`,{},'')).status,401);assert.equal((await api('GET',`/${last.id}/treatment-plans`,{facility_id:f.other})).status,403);
 for(const path of ['/abc/treatment-plans','/1/treatment-plans/no/status','/1/arbitrary']){const r=await fetch(`${base}/hospital-api/dossiers${path}`);assert.equal(r.status,404);assert.equal(r.headers.get('x-test-laravel'),null);}
});
