"use client";

import { useEffect, useRef, useState } from "react";
import { useSearchParams } from "next/navigation";
import { useIdentity } from "../auth/AuthenticatedLayout";
import { apiRequest, AuthError } from "../auth/api";
import { directoryFacility } from "../directory/facilityContext";
import { DirectoryTable } from "../directory/DirectoryPrimitives";
import IdentityPanel from "./IdentityPanel";
import styles from "../clinics/clinics.module.css";

type Patient = { id:number; code:string; first_name:string; family_name:string; birth_date:string|null; gender:string; dossier_id:number|null };
type Card = Omit<Patient,"dossier_id"> & {patient_id:number; status:string; opening_date:string; registration_visit_id:number|null};
type Options = {today:string; can_search:boolean; can_create_patient:boolean; can_register:boolean};

export default function ReceptionScreen() {
  const identity=useIdentity(),params=useSearchParams();
  const {entry}=directoryFacility(identity.access,"reception.view",params.get("facility_id"));
  if(!entry)return <section className={styles.panel}><h2>الاستقبال</h2><p role="alert">لا يتوفر وصول إلى الاستقبال في المشفى المحدد. تواصل مع المسؤول لتعيين صلاحية الاستقبال.</p></section>;
  return <Reception key={entry.facility.id} facility={entry.facility.id} hospital={entry.facility.name_ar}/>;
}

function Reception({facility,hospital}:{facility:number;hospital:string}) {
  const [options,setOptions]=useState<Options|null>(null),[attempt,setAttempt]=useState(0),[query,setQuery]=useState(""),[result,setResult]=useState<{term:string;rows:Patient[]}>({term:"",rows:[]}),[searching,setSearching]=useState(false);
  const [selected,setSelected]=useState<Patient|null>(null),[creating,setCreating]=useState(false),[card,setCard]=useState<Card|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<AuthError|null>(null);
  const [draft,setDraft]=useState({first_name:"",family_name:"",phone:"",birth_date:"",birth_date_accuracy:"unknown",gender:"unknown",address_line:"",displacement_status:"unknown",opening_date:"",visit_date:""});
  const pending=useRef<AbortController|null>(null),reservation=useRef<{body:string;id:string}|null>(null),form=useRef<HTMLFormElement>(null);
  useEffect(()=>()=>pending.current?.abort(),[]);
  useEffect(()=>{const c=new AbortController();apiRequest<Options>(`reception/options?facility_id=${facility}`,{signal:c.signal}).then(v=>{if(!c.signal.aborted){setOptions(v);setDraft(d=>({...d,opening_date:d.opening_date||v.today,visit_date:d.visit_date||v.today}));}}).catch(e=>{if(!c.signal.aborted)setError(e);});return()=>c.abort();},[facility,attempt]);
  useEffect(()=>{const c=new AbortController();const term=query.trim().replace(/\s+/g," ");if(term.length<3||!options?.can_search){return()=>c.abort();}const timer=setTimeout(()=>{setSearching(true);apiRequest<Patient[]>(`reception/patients?facility_id=${facility}&search=${encodeURIComponent(term)}`,{signal:c.signal}).then(v=>{if(!c.signal.aborted)setResult({term,rows:v});}).catch(e=>{if(!c.signal.aborted)setError(e);}).finally(()=>{if(!c.signal.aborted)setSearching(false);});},300);return()=>{clearTimeout(timer);c.abort();};},[facility,query,options?.can_search,attempt]);
  const patients=result.term===query.trim().replace(/\s+/g," ")?result.rows:[];
  async function open(patient:Patient){if(pending.current)return;setSelected(patient);setCreating(false);setCard(null);setError(null);if(!patient.dossier_id)return;const c=new AbortController();pending.current=c;setBusy(true);try{const row=await apiRequest<Card>(`reception/cards/${patient.dossier_id}?facility_id=${facility}`,{signal:c.signal});if(!c.signal.aborted)setCard(row);}catch(e){if(!c.signal.aborted)setError(e as AuthError);}finally{if(pending.current===c)pending.current=null;if(!c.signal.aborted)setBusy(false);}}
  async function save(){if(pending.current||!options?.can_register||(!creating&&!selected)||selected?.dossier_id)return;const c=new AbortController();pending.current=c;setBusy(true);setError(null);const payload={facility_id:facility,...creating?{...draft,person_mode:"new",birth_date:draft.birth_date||null}:{person_mode:"existing",patient_id:selected!.id,opening_date:draft.opening_date,visit_date:draft.visit_date}};const body=JSON.stringify(payload);if(reservation.current?.body!==body)reservation.current={body,id:crypto.randomUUID()};try{const result=await apiRequest<Card>("reception/registrations",{method:"POST",signal:c.signal,body:JSON.stringify({...payload,request_id:reservation.current.id})});if(!c.signal.aborted){setCard(result);setCreating(false);setSelected(null);}}catch(e){if(!c.signal.aborted){setError(e as AuthError);requestAnimationFrame(()=>form.current?.querySelector<HTMLElement>('[aria-invalid="true"]')?.focus());}}finally{if(pending.current===c)pending.current=null;if(!c.signal.aborted)setBusy(false);}}
  function field(key:keyof typeof draft,label:string,type="text"){return <label key={key}>{label}<input aria-label={label} name={key} type={type} value={draft[key]} aria-invalid={!!error?.fields[key]} onChange={e=>setDraft(d=>({...d,[key]:e.target.value}))}/>{error?.fields[key]&&<small role="alert" className={styles.fieldError}>{error.fields[key]}</small>}</label>;}
  return <><header className={styles.heading}><div><h2>الاستقبال وتسجيل المرضى</h2><p>{hospital}</p></div>{options?.can_create_patient&&options.can_register&&<button className={styles.primary} disabled={busy} onClick={()=>{setCreating(true);setSelected(null);setCard(null);setError(null);}}>تسجيل مريض جديد</button>}</header>
    <p className={styles.hint}>ابحث أولًا لتجنب إنشاء هوية مكررة. كود المريض معرّف للنظام وليس رقمًا وطنيًا. هذه الشاشة لا تعرض التاريخ الطبي.</p>
    {error&&<p role="alert">{error.message}<button type="button" className={styles.secondary} disabled={busy} onClick={()=>{setError(null);if(selected?.dossier_id)void open(selected);else setAttempt(v=>v+1);}}>إعادة المحاولة</button></p>}
    {!options&&<p role="status">جارٍ التحقق من صلاحيات الاستقبال…</p>}
    {options && !options.can_search && !options.can_create_patient && <p className={styles.status}>الوصول المحلي إلى الاستقبال متاح؛ البحث وإنشاء هوية المريض ينتظران تفويضًا عالميًا صريحًا من مسؤول النظام.</p>}
    {options?.can_search&&<section className={styles.panel}><label className={styles.search}>البحث بالاسم أو كود المريض<input type="search" value={query} disabled={busy} onChange={e=>{setQuery(e.target.value);setSearching(e.target.value.trim().length>=3);}} placeholder="ثلاثة محارف على الأقل"/></label><p className={styles.hint}>تظهر عشر نتائج كحد أقصى؛ حدّد عبارة البحث عند الحاجة.</p>{searching?<p role="status">جارٍ البحث…</p>:<DirectoryTable label="نتائج الاستقبال المحدودة" headers={["الكود","الاسم","الميلاد","الإجراء"]}>{patients.map(p=><tr key={p.id}><td><bdi>{p.code}</bdi></td><td>{p.first_name} {p.family_name}</td><td>{p.birth_date??"غير معروف"}</td><td><button className={styles.secondary} disabled={busy} onClick={()=>void open(p)}>{p.dossier_id?"فتح ملخص الاستقبال":"اختيار المريض"}</button></td></tr>)}</DirectoryTable>}</section>}
    {card&&<section className={styles.panel} aria-label="ملخص الاستقبال"><h3>{card.first_name} {card.family_name}</h3><p>كود المريض: <bdi>{card.code}</bdi></p><p>حالة الملف: {card.status==="draft"?"مسودة":"فعال"}</p><p>تاريخ التسجيل: {card.opening_date}</p><p>{card.registration_visit_id?"الزيارة الأولى محفوظة؛ يتابع الفريق الطبي الاستكمال من واجهته المصرح بها.":"بطاقة مسجلة في المشفى."}</p></section>}
    {card&&<IdentityPanel key={`${facility}:${card.id}`} facility={facility} id={card.id}/>}
    {(creating||selected&&!selected.dossier_id)&&options?.can_register&&<form ref={form} className={`${styles.panel} ${styles.form}`} noValidate onSubmit={e=>{e.preventDefault();void save();}}><h3>{creating?"مريض جديد وبطاقة وزيارة أولى":`بطاقة وزيارة أولى لـ ${selected?.first_name} ${selected?.family_name}`}</h3><fieldset disabled={busy}><div className={styles.fields}>{creating&&<>{field("first_name","الاسم الأول")}{field("family_name","اسم العائلة")}{field("phone","رقم الهاتف")}{field("birth_date","تاريخ الميلاد","date")}<label>دقة الميلاد<select name="birth_date_accuracy" value={draft.birth_date_accuracy} onChange={e=>setDraft(d=>({...d,birth_date_accuracy:e.target.value}))}><option value="unknown">غير معروف</option><option value="exact">دقيق</option><option value="year_only">السنة فقط</option><option value="estimated">تقديري</option></select></label><label>الجنس<select value={draft.gender} onChange={e=>setDraft(d=>({...d,gender:e.target.value}))}><option value="unknown">غير معروف</option><option value="male">ذكر</option><option value="female">أنثى</option></select></label>{field("address_line","عنوان السكن")}</>}{field("opening_date","تاريخ فتح البطاقة","date")}{field("visit_date","تاريخ الزيارة الأولى","date")}</div></fieldset><div className={styles.actions}><button className={styles.primary} disabled={busy}>{busy?"جارٍ الحفظ…":"حفظ البطاقة والزيارة الأولى"}</button><button type="button" className={styles.secondary} disabled={busy} onClick={()=>{setCreating(false);setSelected(null);}}>إلغاء</button></div><p className={styles.hint}>تبقى البطاقة والزيارة مسودتين حتى يستكملهما الفريق الطبي. كود المريض الجديد يولّده النظام عند نجاح الحفظ.</p></form>}
  </>;
}
